## This is Prompt Learning - Optimization

# Content
## Define Classifier
## Define Datasets
## Define DSPy.Examples
## Define Optimizers
## Define Evaluation
## Run Evaluation
## Save Prompts

# Define classifier

In [1]:
import dspy #the dspy library for building and optimizing language model prompts
import random #often used for shuffling examples in few-shot prompting
import pandas as pd #pandas for data manipulation and analysis
from datasets import load_dataset # Hugging Face datasets library for loading and working with datasets

class Classification(dspy.Signature): #Define what the model should do as task for optimizing the prompt. 
    """Classify the customer message into one of the intent labels.
    The output should be only the predicted class as a single intent label."""

    customer_message = dspy.InputField(desc="Customer message during customer service interaction") # Input field for the customer's message
    intent_labels = dspy.InputField(desc="Labels that represent customer intent") # Input field for the possible intent labels
    answer = dspy.OutputField(desc="a label best matching customer's intent ") # Output field for the predicted intent label

# Use Ollama local llama model instead of OpenAI
# 1. Initialize your local Ollama model using the modern LM client
lm_ollama = dspy.LM(
    'ollama_chat/llama3.2:3b', 
    api_base='http://localhost:11434', 
    max_tokens=512
) # Initialize the Ollama language model with the specified parameters
dspy.settings.configure(lm=lm_ollama) # Configure dspy to use the Ollama language model for all subsequent operations
#dspy.predict()
cot_predictor = dspy.ChainOfThought(Classification) # Create a Chain of Thought predictor using the Classification signature RAtionales (CoT) approach

21:14:23 - LiteLLM:WARNING: common_utils.py:979 - litellm: could not pre-load bedrock-runtime response stream shape — Bedrock event-stream decoding will be unavailable. Error: No module named 'botocore'
21:14:23 - LiteLLM:WARNING: common_utils.py:24 - litellm: could not pre-load sagemaker-runtime response stream shape — SageMaker event-stream decoding will be unavailable. Error: No module named 'botocore'

# Parse Atis Dataset

In [2]:
dataset = load_dataset("tuetschek/atis")
dataset.set_format(type="pandas") #define the format of the dataset to be pandas DataFrame for easier manipulation

df_train: pd.DataFrame = dataset["train"][:] #train set as a pandas DataFrame
df_test: pd.DataFrame = dataset["test"][:] #test set as a pandas DataFrame
small_test = df_test.head(100) #take a small subset of the test set for quicker evaluation

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## x column: text, y column: intent

In [3]:
df_train.iloc[0]

id                                                        0
intent                                               flight
text      i want to fly from boston at 838 am and arrive...
slots     O O O O O B-fromloc.city_name O B-depart_time....
Name: 0, dtype: object

## prepare labels

In [4]:
labels = df_train["intent"].unique().tolist()
labels_str = "%".join(labels)
labels_str
#"~|"

'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'

In [5]:
## run prediction
first_row = df_train.iloc[0]
print(f"customer message: {first_row['text']},real class: {first_row['intent']}")
cot_predictor(customer_message=first_row["text"], intent_labels=labels_str)

customer message: i want to fly from boston at 838 am and arrive in denver at 1110 in the morning,real class: flight

Prediction(
    reasoning='The customer message contains specific details about a flight from Boston to Denver, including departure time, arrival time, airline, and city.',
    answer='flight_time'
)

In [6]:
cot_predictor.save("cot_zero_shot_firstattempt.json")

In [7]:
cot_predictor.history

[{'prompt': None,
  'messages': [{'role': 'system',
    'content': "Your input fields are:\n1. `customer_message` (str): Customer message during customer service interaction\n2. `intent_labels` (str): Labels that represent customer intent\nYour output fields are:\n1. `reasoning` (str): \n2. `answer` (str): a label best matching customer's intent\nAll interactions will be structured in the following way, with the appropriate values filled in.\n\n[[ ## customer_message ## ]]\n{customer_message}\n\n[[ ## intent_labels ## ]]\n{intent_labels}\n\n[[ ## reasoning ## ]]\n{reasoning}\n\n[[ ## answer ## ]]\n{answer}\n\n[[ ## completed ## ]]\nIn adhering to this structure, your objective is: \n        Classify the customer message into one of the intent labels.\n        The output should be only the predicted class as a single intent label."},
   {'role': 'user',
    'content': '[[ ## customer_message ## ]]\ni want to fly from boston at 838 am and arrive in denver at 1110 in the morning\n\n[[ ## intent_labels ## ]]\nflight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no\n\nRespond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.'}],
  'kwargs': {},
  'response': ModelResponse(id='chatcmpl-19ab4f02-0a73-45e5-9956-9ec65bc3059e', created=1779465005, model='ollama_chat/llama3.2:3b', object='chat.completion', system_fingerprint=None, choices=[Choices(finish_reason='stop', index=0, message=Message(content='[[ ## reasoning ## ]]\nThe customer message contains specific details about a flight from Boston to Denver, including departure time, arrival time, airline, and city.\n\n[[ ## answer ## ]]\nflight_time\n\n[[ ## completed ## ]]', role='assistant', tool_calls=None, function_call=None, provider_specific_fields=None))], usage={}, cache_hit=True),
  'outputs': ['[[ ## reasoning ## ]]\nThe customer message contains specific details about a flight from Boston to Denver, including departure time, arrival time, airline, and city.\n\n[[ ## answer ## ]]\nflight_time\n\n[[ ## completed ## ]]'],
  'usage': {},
  'cost': 0.0,
  'timestamp': '2026-06-05T21:14:32.332159',
  'uuid': 'ac515fe1-e355-4367-b68d-65cf2abcbe13',
  'model': 'ollama_chat/llama3.2:3b',
  'response_model': 'ollama_chat/llama3.2:3b',
  'model_type': 'chat'}]

# Define Examples

In [8]:
import random
import dspy

# 1. Fixed the uppercase "Example" in the type hint
def get_dspy_examples(df, k) -> list[dspy.Example]:
    dspy_examples = []
    for label in labels:
        try:
            label_df = df[df["intent"] == label].sample(n=k)
            for index, row in label_df.iterrows():
                dspy_examples.append(
                    dspy.Example(
                        customer_message=row["text"], 
                        answer=row["intent"], 
                        intent_labels=labels_str
                    ).with_inputs("customer_message", "intent_labels")
                )
        except ValueError:
            # specifically catch sample size errors if a class has < k items
            continue

    return dspy_examples

# Generate your datasets
train_examples = get_dspy_examples(df_train, k=2)
all_test_examples = get_dspy_examples(df_test, k=10)

# 2. Fixed the splitting logic using indices so DSPy Example identities stay intact
print(f"Total test pool: {len(all_test_examples)}")

# Shuffle indices safely
indices = list(range(len(all_test_examples)))
random.shuffle(indices)

split_idx = len(indices) // 2
dev_indices = set(indices[:split_idx])

dev_examples = [all_test_examples[i] for i in dev_indices]
test_examples = [all_test_examples[i] for i in range(len(all_test_examples)) if i not in dev_indices]

print(f"Dev size: {len(dev_examples)} | Test size: {len(test_examples)}")

Total test pool: 90
Dev size: 45 | Test size: 45

In [9]:
train_examples

[Example({'customer_message': 'show me flights from denver to washington dc wednesday', 'answer': 'flight', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what flights from atlanta to toronto', 'answer': 'flight', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': "what is american 's schedule of morning flights to atlanta", 'answer': 'flight_time', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what time does the tuesday morning 755 flight leaving washington arrive in san francisco', 'answer': 'flight_time', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'could you please find me the cheapest one way fare from boston to philadelphia', 'answer': 'airfare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me the lowest fare for a round trip flight from baltimore to dallas', 'answer': 'airfare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what type of aircraft flies from pittsburgh to baltimore', 'answer': 'aircraft', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what kind of airplanes are used by delta airlines flying between washington and denver', 'answer': 'aircraft', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'ground transportation in las vegas', 'answer': 'ground_service', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'tell me about ground transportation at salt lake city', 'answer': 'ground_service', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'please show me all airports in denver', 'answer': 'airport', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what airport in new york is closest to downtown', 'answer': 'airport', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what airlines fly from boston to atlanta', 'answer': 'airline', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what airlines fly from boston to atlanta', 'answer': 'airline', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how long does it take to get from denver to oakland', 'answer': 'distance', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how long is a trip from philadelphia airport to downtown philadelphia', 'answer': 'distance', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what is mco', 'answer': 'abbreviation', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what does the fare code f mean', 'answer': 'abbreviation', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what are the rental car rates in dallas', 'answer': 'ground_fare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how much is a limousine between dallas fort worth international airport and dallas', 'answer': 'ground_fare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how many cities are served by twa with first class flights', 'answer': 'quantity', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how many first class flights does united have leaving from all cities today', 'answer': 'quantity', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what cities does continental service', 'answer': 'city', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me city served both by nationair and canadian airlines international', 'answer': 'city', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'may i have a listing of flight numbers from columbus ohio to minneapolis minnesota on monday', 'answer': 'flight_no', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what is the flight number for the continental flight which leaves denver at 1220 pm and goes to san francisco', 'answer': 'flight_no', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': "what 's the capacity of a 733", 'answer': 'capacity', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how many seats in a 100', 'answer': 'capacity', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show all flights and fares from denver to san francisco', 'answer': 'flight+airfare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me all flights and fares from denver to san francisco', 'answer': 'flight+airfare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what are all the available meals', 'answer': 'meal', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me all meals on flights from atlanta to washington', 'answer': 'meal', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what is restriction ap57', 'answer': 'restriction', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what are the air restrictions on flights from pittsburgh to atlanta for the airfare of 416 dollars', 'answer': 'restriction', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'may i please see airlines and flight numbers from new york to toronto on the same date june seventeenth also arriving in toronto before noon thank you', 'answer': 'airline+flight_no', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'airline and flight number from columbus to minneapolis', 'answer': 'airline+flight_no', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'})]

# Define LabeledFewShot Optimizer
LabeledFewShot is the simplest optimizer. Its compile method injects samples intro the prompt.
There is not optimization going on.

In [10]:
from dspy.teleprompt import LabeledFewShot

few_shot_demos = random.sample(train_examples, k=10)
labeled_fewshot_optimizer = LabeledFewShot(k=len(few_shot_demos))
few_shot_model = labeled_fewshot_optimizer.compile(student=cot_predictor, trainset=few_shot_demos)

In [11]:
few_shot_demos

[Example({'customer_message': 'show me the lowest fare for a round trip flight from baltimore to dallas', 'answer': 'airfare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': "what 's the capacity of a 733", 'answer': 'capacity', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me all meals on flights from atlanta to washington', 'answer': 'meal', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what are the air restrictions on flights from pittsburgh to atlanta for the airfare of 416 dollars', 'answer': 'restriction', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me city served both by nationair and canadian airlines international', 'answer': 'city', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what cities does continental service', 'answer': 'city', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what are all the available meals', 'answer': 'meal', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'show me all flights and fares from denver to san francisco', 'answer': 'flight+airfare', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'what is mco', 'answer': 'abbreviation', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'}),
 Example({'customer_message': 'how many seats in a 100', 'answer': 'capacity', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'})]

### What is happenning under the hood?
### LabeledFewShot randomly selects labels

### DSPy SOURCE CODE: https://github.com/stanfordnlp/dspy/blob/793530c65a0e1721997dac0d2636f0f70ad649b6/dspy/teleprompt/vanilla.py#L6

class LabeledFewShot(Teleprompter):
    def __init__(self, k=16):
        self.k = k

    def compile(self, student, *, trainset, sample=True):
        self.student = student.reset_copy()
        self.trainset = trainset

        if len(self.trainset) == 0:
            return self.student

        rng = random.Random(0)

        for predictor in self.student.predictors():
            if sample:
                predictor.demos = rng.sample(self.trainset, min(self.k, len(self.trainset)))
            else:
                predictor.demos = self.trainset[: min(self.k, len(self.trainset))]

        return self.student

### My own summary of the implementation
DSPy samples randomly a portion of the samples as examples for in-context learning. 
There's no actual optimization process.

### How does the prompt looks like?

In [12]:
example = test_examples[0]
# without inputs(), we won't inject the inputs of the example
pred = few_shot_model(**example.inputs())
# Produce a prediction from our `cot` module, using the `example` above as input.
print("Prediction:", pred)
# Note: inspect_history() is specific to OpenAI. For Ollama, you can print the prediction directly.

Prediction: Prediction(
    reasoning='The customer is looking for a nonstop flight from St. Petersburg to Charlotte that leaves in the afternoon and arrives as soon after 5 pm as possible.',
    answer='flight+airfare'
)

## Define BootstrapFewShot Optimizer
This family of optimizers is focused on optimizing the few shot examples. Let's take an example of a Sample pipeline and see how we can use this optimizer to optimize it. From: https://dspy.ai/deep-dive/optimizers/bootstrap-fewshot/

In [13]:
from dspy.evaluate import answer_exact_match as metric
from dspy.teleprompt import BootstrapFewShot

optimizer = BootstrapFewShot(
    metric=metric, #grading rules
    max_bootstrapped_demos=10, #number of examples to be generated by the model and added to the training set in each round Rationale + answer
    max_labeled_demos=10, #the limit for unaltered training examples that can be added to the training set in each round
    max_rounds=10, #If synthetic generation of few shot examples does not lead to improvement, the optimization process will stop after 10 rounds
)

### Optimize

In [14]:
# documentation is wrong - there is not valset: https://dspy.ai/deep-dive/optimizers/bootstrap-fewshot/
cot_few_shot_optimized = optimizer.compile(cot_predictor, trainset=train_examples)

 33%|███▎      | 12/36 [04:56<09:52, 24.68s/it]

Bootstrapped 10 full traces after 12 examples for up to 10 rounds, amounting to 36 attempts.

## Peek under the hood of DSPy source code for BootStrapFewShot training

### DSPy source code for training
class BootstrapFewShot()
    def _train(self):
        rng = random.Random(0)
        raw_demos = self.validation

        for name, predictor in self.student.named_predictors():
            augmented_demos = self.name2traces[name][: self.max_bootstrapped_demos]

            sample_size = min(self.max_labeled_demos - len(augmented_demos), len(raw_demos))
            sample_size = max(0, sample_size)

            raw_demos = rng.sample(raw_demos, sample_size)

            if dspy.settings.release >= 20230928:
                predictor.demos = raw_demos + augmented_demos
            else:
                predictor.demos = augmented_demos + raw_demos

        return self.student

I consulted with ChatGPT about this method. Source code: https://github.com/stanfordnlp/dspy/blob/main/dspy/teleprompt/bootstrap.py

_train() Purpose
Once _bootstrap() has collected and validated a set of bootstrapped demos, _train() takes over to:

Compile Final Demos for Predictors: _train() assembles the demos (both bootstrapped and labeled) for each predictor within the student model. For each predictor, it selects a mix of bootstrapped demos (from _bootstrap()) and labeled examples (raw demos from the validation set) to create a final demo set.
Random Sampling: The method performs a random sample from the raw labeled demos, ensuring the demos meet the configuration limits, such as max_labeled_demos.
Set Demos for Each Predictor: Finally, _train() updates each predictor in the student model with this finalized set of demos, effectively preparing it for use.
In essence, _bootstrap() is responsible for creating and validating bootstrapped demos, while _train() assembles a balanced set of these demos and labeled examples to finalize the student model’s training.

### My Own Summary
BootstrapFewShot has two main properties:
1. Enable you to generate additional examples
2. DSPy tests which predictions pass the validation and keep only those

## Define BootstrapFewShotWithRandomSearch

In [15]:
from dspy.teleprompt import BootstrapFewShotWithRandomSearch

optimizer = BootstrapFewShotWithRandomSearch(
    metric=metric, 
    max_bootstrapped_demos=10, 
    max_labeled_demos=10,
    num_threads=10,
    num_candidate_programs=5
)

Going to sample between 1 and 10 traces per predictor.
Will attempt to bootstrap 5 candidate sets.

In [16]:
# THE CORRECT LINE:
cot_few_shot_rs_optimized = optimizer.compile(
    student=cot_predictor, 
    trainset=train_examples, 
    valset=dev_examples 
)

Average Metric: 1.00 / 1 (100.0%):   0%|          | 0/45 [00:00<?, ?it/s]

Average Metric: 16.00 / 45 (35.6%): 100%|██████████| 45/45 [03:04<00:00,  4.10s/it]

2026/06/05 21:23:36 INFO dspy.evaluate.evaluate: Average Metric: 16 / 45 (35.6%)

New best score: 35.56 for seed -3
Scores so far: [35.56]
Best score so far: 35.56
Average Metric: 32.00 / 45 (71.1%): 100%|██████████| 45/45 [05:21<00:00,  7.15s/it]

2026/06/05 21:28:58 INFO dspy.evaluate.evaluate: Average Metric: 32 / 45 (71.1%)

New best score: 71.11 for seed -2
Scores so far: [35.56, 71.11]
Best score so far: 71.11

 36%|███▌      | 13/36 [00:15<00:27,  1.18s/it]

Bootstrapped 10 full traces after 13 examples for up to 1 rounds, amounting to 13 attempts.
Average Metric: 24.00 / 45 (53.3%): 100%|██████████| 45/45 [06:47<00:00,  9.06s/it]

2026/06/05 21:36:01 INFO dspy.evaluate.evaluate: Average Metric: 24 / 45 (53.3%)

Scores so far: [35.56, 71.11, 53.33]
Best score so far: 71.11

 33%|███▎      | 12/36 [02:23<04:46, 11.93s/it]

Bootstrapped 7 full traces after 12 examples for up to 1 rounds, amounting to 12 attempts.
Average Metric: 25.00 / 45 (55.6%): 100%|██████████| 45/45 [03:45<00:00,  5.00s/it]

2026/06/05 21:42:09 INFO dspy.evaluate.evaluate: Average Metric: 25 / 45 (55.6%)

Scores so far: [35.56, 71.11, 53.33, 55.56]
Best score so far: 71.11

 14%|█▍        | 5/36 [00:26<02:46,  5.38s/it]

Bootstrapped 3 full traces after 5 examples for up to 1 rounds, amounting to 5 attempts.
Average Metric: 21.00 / 45 (46.7%): 100%|██████████| 45/45 [02:11<00:00,  2.91s/it]

2026/06/05 21:44:47 INFO dspy.evaluate.evaluate: Average Metric: 21 / 45 (46.7%)

Scores so far: [35.56, 71.11, 53.33, 55.56, 46.67]
Best score so far: 71.11

  8%|▊         | 3/36 [00:16<03:03,  5.57s/it]

Bootstrapped 1 full traces after 3 examples for up to 1 rounds, amounting to 3 attempts.
Average Metric: 24.00 / 45 (53.3%): 100%|██████████| 45/45 [01:59<00:00,  2.65s/it]

2026/06/05 21:47:03 INFO dspy.evaluate.evaluate: Average Metric: 24 / 45 (53.3%)

Scores so far: [35.56, 71.11, 53.33, 55.56, 46.67, 53.33]
Best score so far: 71.11

 19%|█▉        | 7/36 [00:37<02:36,  5.39s/it]

Bootstrapped 4 full traces after 7 examples for up to 1 rounds, amounting to 7 attempts.
Average Metric: 22.00 / 45 (48.9%): 100%|██████████| 45/45 [01:58<00:00,  2.62s/it]

2026/06/05 21:49:39 INFO dspy.evaluate.evaluate: Average Metric: 22 / 45 (48.9%)

Scores so far: [35.56, 71.11, 53.33, 55.56, 46.67, 53.33, 48.89]
Best score so far: 71.11

 19%|█▉        | 7/36 [00:36<02:30,  5.19s/it]

Bootstrapped 4 full traces after 7 examples for up to 1 rounds, amounting to 7 attempts.
Average Metric: 29.00 / 45 (64.4%): 100%|██████████| 45/45 [02:23<00:00,  3.19s/it]

2026/06/05 21:52:39 INFO dspy.evaluate.evaluate: Average Metric: 29 / 45 (64.4%)

Scores so far: [35.56, 71.11, 53.33, 55.56, 46.67, 53.33, 48.89, 64.44]
Best score so far: 71.11
8 candidate programs found.

## Peek under the hood of the source code Implementation

### Source code
From: https://github.com/stanfordnlp/dspy/blob/main/dspy/teleprompt/random_search.py

       assert seed >= 0, seed

        random.Random(seed).shuffle(trainset_copy)
        size = random.Random(seed).randint(self.min_num_samples, self.max_num_samples)

        optimizer = BootstrapFewShot(
            metric=self.metric,
            metric_threshold=self.metric_threshold,
            max_bootstrapped_demos=size,
            max_labeled_demos=self.max_labeled_demos,
            teacher_settings=self.teacher_settings,
            max_rounds=self.max_rounds,
            max_errors=self.max_errors,
        )

        program = optimizer.compile(student, teacher=teacher, trainset=trainset_copy)

    evaluate = Evaluate(
        devset=self.valset,
        metric=self.metric,
        num_threads=self.num_threads,
        max_errors=self.max_errors,
        display_table=False,
        display_progress=True,
    )

    score, subscores = evaluate(program, return_all_scores=True)

    all_subscores.append(subscores)

### My own summary
Given the number of programs we will generate each time a different seed and run BootStrapFewShot with that

# Evaluation

## Single Evaluation

In [17]:
from dspy.evaluate import answer_exact_match

# Instantiate the metric.
metric = answer_exact_match

example = test_examples[0]
# Produce a prediction from our `cot` module, using the `example` above as input.
print(example)
pred = cot_predictor(**example.inputs())
print(pred)

# Compute the metric score for the prediction.
score = metric(example, pred)

print(f"Customer message: \t {example.customer_message}\n")
print(f"Gold Response: \t {example.answer}\n")
print(f"Predicted Response: \t {pred.answer}\n")
print(f"Exact match score: {score:.2f}")

Example({'customer_message': 'find a flight between st. petersburg and charlotte the flight should leave in the afternoon and arrive as soon after 5 pm as possible it should be a nonstop flight', 'answer': 'flight', 'intent_labels': 'flight%flight_time%airfare%aircraft%ground_service%airport%airline%distance%abbreviation%ground_fare%quantity%city%flight_no%capacity%flight+airfare%meal%restriction%airline+flight_no%ground_service+ground_fare%airfare+flight_time%cheapest%aircraft+flight+flight_no'}) (input_keys={'customer_message', 'intent_labels'})
Prediction(
    reasoning='The customer message requires finding a nonstop flight from St. Petersburg to Charlotte that departs in the afternoon, arrives as soon after 5 pm as possible, and has the earliest arrival time.',
    answer='flight%cheapest%'
)
Customer message: 	 find a flight between st. petersburg and charlotte the flight should leave in the afternoon and arrive as soon after 5 pm as possible it should be a nonstop flight

Gold Response: 	 flight

Predicted Response: 	 flight%cheapest%

Exact match score: 0.00

## Setup Evaluation

In [18]:
from dspy.evaluate.evaluate import Evaluate
# Set up the `evaluate_atis` function. We'll use this many times below.
print(len(train_examples))
evaluate_atis = Evaluate(devset=test_examples, num_threads=8, display_progress=True, display_table=5, provide_traceback=True)

36

## Evaluate zero shot CoT

In [19]:
# Evaluate the program with the `answer_exact_match` metric.
# Launch evaluation.
evaluate_atis(cot_predictor, metric=metric)

Average Metric: 11.00 / 45 (24.4%): 100%|██████████| 45/45 [01:26<00:00,  1.92s/it]

2026/06/05 21:54:09 INFO dspy.evaluate.evaluate: Average Metric: 11 / 45 (24.4%)

,customer_message,example_answer,intent_labels,reasoning,pred_answer,answer_exact_match
0,find a flight between st. petersburg and charlotte the flight shou...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer message requires finding a nonstop flight from St. Pe...,flight%cheapest%,✔️ [False]
1,get flights from detroit to toronto,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"The customer message ""get flights from detroit to toronto"" is rela...",flight%airfare%city%airline%distance%\n\n[[ ## completed ## ]),✔️ [False]
2,what flights go from phoenix to salt lake city,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer message is asking about flights from Phoenix to Salt ...,flight%airfare%city%flight_no%,✔️ [False]
3,list all flights arriving in denver between 8 and 9 pm,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is requesting information about flights arriving in D...,flight%aircraft%city%airport%airline%distance%abbreviation%,✔️ [False]
4,can you find me a flight from salt lake city to new york city next...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer message can be classified as a query for booking a fl...,flight%airline%cheapest,✔️ [False]

EvaluationResult(score=24.44, results=<list of 45 results>)

## Evaluate few shot CoT

In [20]:
evaluate_atis(few_shot_model, metric=metric)

Average Metric: 34.00 / 45 (75.6%): 100%|██████████| 45/45 [01:58<00:00,  2.64s/it]

2026/06/05 21:56:08 INFO dspy.evaluate.evaluate: Average Metric: 34 / 45 (75.6%)

,customer_message,example_answer,intent_labels,reasoning,pred_answer,answer_exact_match
0,find a flight between st. petersburg and charlotte the flight shou...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is looking for a nonstop flight from St. Petersburg t...,flight+airfare,✔️ [False]
1,get flights from detroit to toronto,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,Not supplied for this particular example.,flight,✔️ [True]
2,what flights go from phoenix to salt lake city,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,Not supplied for this particular example.,flight,✔️ [True]
3,list all flights arriving in denver between 8 and 9 pm,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"The customer message is asking for a specific flight schedule, so ...",flight_no,✔️ [False]
4,can you find me a flight from salt lake city to new york city next...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer message is specifying a very specific flight schedule...,flight,✔️ [True]

EvaluationResult(score=75.56, results=<list of 45 results>)

## Evaluate BootstrapedFewShot

In [21]:
evaluate_atis(cot_few_shot_optimized, metric=metric)

Average Metric: 32.00 / 45 (71.1%): 100%|██████████| 45/45 [02:40<00:00,  3.57s/it]

2026/06/05 21:58:49 INFO dspy.evaluate.evaluate: Average Metric: 32 / 45 (71.1%)

,customer_message,example_answer,intent_labels,reasoning,pred_answer,answer_exact_match
0,find a flight between st. petersburg and charlotte the flight shou...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,To find a flight between St. Petersburg and Charlotte that meets t...,airfare,✔️ [False]
1,get flights from detroit to toronto,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer message is asking for flights from Detroit to Toronto...,flight,✔️ [True]
2,what flights go from phoenix to salt lake city,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"Not supplied for this particular example. However, to provide a he...",flight,✔️ [True]
3,list all flights arriving in denver between 8 and 9 pm,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,To generate a list of flights arriving in Denver between 8 and 9 p...,flight_time,✔️ [False]
4,can you find me a flight from salt lake city to new york city next...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,To find a flight from Salt Lake City to New York City next Saturda...,flight,✔️ [True]

EvaluationResult(score=71.11, results=<list of 45 results>)

## Evaluate Boostraped Random Search

In [22]:
evaluate_atis(cot_few_shot_rs_optimized, metric=metric)

Average Metric: 29.00 / 45 (64.4%): 100%|██████████| 45/45 [02:14<00:00,  2.99s/it]

2026/06/05 22:01:03 INFO dspy.evaluate.evaluate: Average Metric: 29 / 45 (64.4%)

,customer_message,example_answer,intent_labels,reasoning,pred_answer,answer_exact_match
0,find a flight between st. petersburg and charlotte the flight shou...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is looking for a nonstop flight from St. Petersburg t...,flight_no,✔️ [False]
1,get flights from detroit to toronto,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,Not supplied for this particular example.,flight_no,✔️ [False]
2,what flights go from phoenix to salt lake city,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is asking for a list of flights from Phoenix to Salt ...,flight_no,✔️ [False]
3,list all flights arriving in denver between 8 and 9 pm,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,Not supplied for this particular example.,flight_no,✔️ [False]
4,can you find me a flight from salt lake city to new york city next...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"The customer is looking for a specific flight on a specific date, ...",airfare,✔️ [False]

EvaluationResult(score=64.44, results=<list of 45 results>)

# Save / Load models

In [23]:
cot_predictor.save("cot_zero_shot.json")
few_shot_model.save("cot_few_shot.json")
cot_few_shot_optimized.save("cot_boostraped_few_shot.json")
cot_few_shot_rs_optimized.save("cot_bootstraped_rs_few_shot.json")

In [24]:
cot_predictor.load("cot_zero_shot.json")
few_shot_model.load("cot_few_shot.json")
cot_few_shot_optimized.load("cot_boostraped_few_shot.json")
cot_few_shot_rs_optimized.load("cot_bootstraped_rs_few_shot.json")

In [25]:
import dspy
from dspy.teleprompt import MIPROv2

# 1. Initialize the MIPROv2 optimizer
mipro_optimizer = MIPROv2(
    metric=metric,
    num_threads=10,
    auto="light" 
)

# 2. Compile your program 
few_shot_model = mipro_optimizer.compile(
    student=cot_predictor, 
    trainset=train_examples,
    valset=dev_examples, # Updated to use your 'test_examples' dataset
    requires_permission_to_run=False
)

2026/06/05 22:01:03 WARNING dspy.teleprompt.mipro_optimizer_v2: 'requires_permission_to_run' is deprecated and will be removed in a future version.
2026/06/05 22:01:03 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 10
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 45

2026/06/05 22:01:03 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2026/06/05 22:01:03 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2026/06/05 22:01:03 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

 19%|█▉        | 7/36 [00:20<01:23,  2.87s/it]

Bootstrapped 4 full traces after 7 examples for up to 1 rounds, amounting to 7 attempts.
Bootstrapping set 4/6

  3%|▎         | 1/36 [00:05<03:24,  5.83s/it]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.
Bootstrapping set 5/6

  8%|▊         | 3/36 [00:12<02:13,  4.04s/it]

Bootstrapped 2 full traces after 3 examples for up to 1 rounds, amounting to 3 attempts.
Bootstrapping set 6/6

  3%|▎         | 1/36 [00:05<03:24,  5.85s/it]
2026/06/05 22:01:47 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2026/06/05 22:01:47 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.

2026/06/05 22:03:16 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2026/06/05 22:03:17 WARNING dspy.predict.predict: Input contains fields not in signature. These fields will be ignored: ['max_depth']. Expected fields: ['program_code', 'program_example', 'program_description', 'module'].
2026/06/05 22:03:17 WARNING dspy.predict.predict: Input contains fields not in signature. These fields will be ignored: ['tip', 'previous_instructions']. Expected fields: ['dataset_description', 'program_code', 'program_description', 'module', 'module_description', 'task_demos', 'basic_instruction'].
2026/06/05 22:03:44 WARNING dspy.predict.predict: Input contains fields not in signature. These fields will be ignored: ['max_depth']. Expected fields: ['program_code', 'program_example', 'program_description', 'module'].
2026/06/05 22:03:57 WARNING dspy.predict.predict: Input contains fields not in signature. These fields will be ignored: ['previous_instructions']. Expected fields: ['dataset_description', 'program_code', 'program_description', 'module', 'module_description', 'task_demos', 'basic_instruction', 'tip'].
2026/06/05 22:04:25 WARNING dspy.predict.predict: Input contains fields not in signature. These fields will be ignored: ['max_depth']. Expected fields: ['program_code', 'program_example', 'program_description', 'module'].
2026/06/05 22:04:35 WARNING dspy.predict.predict: Input contains fields not in signature. These fields will be ignored: ['previous_instructions']. Expected fields: ['dataset_description', 'program_code', 'program_description', 'module', 'module_description', 'task_demos', 'basic_instruction', 'tip'].
2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Classify the customer message into one of the intent labels.
The output should be only the predicted class as a single intent label.

2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Classify customer message into one of flight%airfare intent labels, providing only the predicted class as a single intent label.

2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: 2: To better classify customer messages, propose an instruction that incorporates a more nuanced understanding of intent labels, including phrases or keywords not explicitly defined in the existing intent labels. For example, consider adding "specific flight" and "round trip" to expand the range of recognized intent labels.

Additionally, suggest using techniques like entity recognition to identify specific details mentioned in the customer message (e.g., cities, flight numbers, fare types) to further inform the classification process.

2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2:

2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 10 - Full Evaluation of Default Program ==

Average Metric: 16.00 / 45 (35.6%): 100%|██████████| 45/45 [00:00<00:00, 639.05it/s]

2026/06/05 22:04:48 INFO dspy.evaluate.evaluate: Average Metric: 16 / 45 (35.6%)
2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 35.56

/opt/anaconda3/envs/dspy/lib/python3.10/site-packages/optuna/_experimental.py:33: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  optuna_warn(
2026/06/05 22:04:48 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 10 =====

Average Metric: 22.00 / 45 (48.9%): 100%|██████████| 45/45 [02:30<00:00,  3.35s/it]

2026/06/05 22:07:19 INFO dspy.evaluate.evaluate: Average Metric: 22 / 45 (48.9%)
2026/06/05 22:07:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 48.89
2026/06/05 22:07:19 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.89 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3'].
2026/06/05 22:07:19 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89]
2026/06/05 22:07:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 48.89
2026/06/05 22:07:19 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:07:19 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 10 =====

Average Metric: 5.00 / 45 (11.1%): 100%|██████████| 45/45 [07:06<00:00,  9.47s/it]

2026/06/05 22:14:25 INFO dspy.evaluate.evaluate: Average Metric: 5 / 45 (11.1%)
2026/06/05 22:14:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 11.11 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0'].
2026/06/05 22:14:25 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11]
2026/06/05 22:14:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 48.89
2026/06/05 22:14:25 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:14:25 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 10 =====

Average Metric: 22.00 / 45 (48.9%): 100%|██████████| 45/45 [02:37<00:00,  3.50s/it]

2026/06/05 22:17:02 INFO dspy.evaluate.evaluate: Average Metric: 22 / 45 (48.9%)
2026/06/05 22:17:02 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.89 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5'].
2026/06/05 22:17:02 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89]
2026/06/05 22:17:02 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 48.89
2026/06/05 22:17:02 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:17:02 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 10 =====

Average Metric: 25.00 / 45 (55.6%): 100%|██████████| 45/45 [03:07<00:00,  4.16s/it]

2026/06/05 22:20:10 INFO dspy.evaluate.evaluate: Average Metric: 25 / 45 (55.6%)
2026/06/05 22:20:10 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 55.56
2026/06/05 22:20:10 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 55.56 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2'].
2026/06/05 22:20:10 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56]
2026/06/05 22:20:10 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:20:10 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:20:10 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 10 =====

Average Metric: 22.00 / 45 (48.9%): 100%|██████████| 45/45 [02:20<00:00,  3.13s/it]

2026/06/05 22:22:30 INFO dspy.evaluate.evaluate: Average Metric: 22 / 45 (48.9%)
2026/06/05 22:22:30 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.89 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5'].
2026/06/05 22:22:30 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56, 48.89]
2026/06/05 22:22:30 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:22:30 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:22:30 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 10 =====

Average Metric: 5.00 / 45 (11.1%): 100%|██████████| 45/45 [00:00<00:00, 366.91it/s]

2026/06/05 22:22:31 INFO dspy.evaluate.evaluate: Average Metric: 5 / 45 (11.1%)
2026/06/05 22:22:31 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 11.11 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0'].
2026/06/05 22:22:31 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56, 48.89, 11.11]
2026/06/05 22:22:31 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:22:31 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:22:31 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 10 =====

Average Metric: 7.00 / 45 (15.6%): 100%|██████████| 45/45 [03:54<00:00,  5.22s/it]

2026/06/05 22:26:25 INFO dspy.evaluate.evaluate: Average Metric: 7 / 45 (15.6%)
2026/06/05 22:26:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 15.56 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5'].
2026/06/05 22:26:25 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56, 48.89, 11.11, 15.56]
2026/06/05 22:26:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:26:25 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:26:25 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 10 =====

Average Metric: 23.00 / 45 (51.1%): 100%|██████████| 45/45 [02:36<00:00,  3.49s/it]

2026/06/05 22:29:02 INFO dspy.evaluate.evaluate: Average Metric: 23 / 45 (51.1%)
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 51.11 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 4'].
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56, 48.89, 11.11, 15.56, 51.11]
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 10 =====

Average Metric: 7.00 / 45 (15.6%): 100%|██████████| 45/45 [00:00<00:00, 527.25it/s]

2026/06/05 22:29:02 INFO dspy.evaluate.evaluate: Average Metric: 7 / 45 (15.6%)
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 15.56 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5'].
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56, 48.89, 11.11, 15.56, 51.11, 15.56]
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2026/06/05 22:29:02 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 10 =====

Average Metric: 25.00 / 45 (55.6%): 100%|██████████| 45/45 [00:00<00:00, 596.80it/s]

2026/06/05 22:29:03 INFO dspy.evaluate.evaluate: Average Metric: 25 / 45 (55.6%)
2026/06/05 22:29:03 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 55.56 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2'].
2026/06/05 22:29:03 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [35.56, 48.89, 11.11, 48.89, 55.56, 48.89, 11.11, 15.56, 51.11, 15.56, 55.56]
2026/06/05 22:29:03 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 55.56
2026/06/05 22:29:03 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2026/06/05 22:29:03 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 55.56!

In [26]:
evaluate_atis(few_shot_model, metric=metric)

Average Metric: 24.00 / 45 (53.3%): 100%|██████████| 45/45 [02:57<00:00,  3.94s/it]

2026/06/05 22:32:00 INFO dspy.evaluate.evaluate: Average Metric: 24 / 45 (53.3%)

,customer_message,example_answer,intent_labels,reasoning,pred_answer,answer_exact_match
0,find a flight between st. petersburg and charlotte the flight shou...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"To find a suitable flight, we need to look for a non-stop afternoo...",airfare,✔️ [False]
1,get flights from detroit to toronto,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is requesting a general query for flights from Detroi...,flight,✔️ [True]
2,what flights go from phoenix to salt lake city,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is asking about general flights from Phoenix to Salt ...,flight,✔️ [True]
3,list all flights arriving in denver between 8 and 9 pm,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"The customer is asking for a specific flight schedule, requiring m...",flight schedule or flight times,✔️ [False]
4,can you find me a flight from salt lake city to new york city next...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The customer is asking for a specific flight from Salt Lake City t...,airfare,✔️ [False]

EvaluationResult(score=53.33, results=<list of 45 results>)

In [27]:
few_shot_model.save("MiproV2Prompt.json")

In [ ]:
import dspy
import os

# 1. Define the Reflection Model for GEPA
# This model acts as the teacher to diagnose errors and rewrite your prompt
reflection_model = dspy.LM("openai/gpt-5") 

os.environ["OPENAI_API_KEY"] = "USE-YOUR-OWN-KEY" # Set your OpenAI API key as an environment variable for authentication
# 2. Define the Metric Function EXACTLY as GEPA expects it
def my_metric(gold, pred, trace=None, pred_name=None, pred_trace=None):
    """
    Evaluates if the predicted intent matches the actual ground truth intent.
    Accepts all 5 arguments required by the GEPA optimizer.
    """
    # Safely extract the prediction string
    predicted_intent = pred.answer.strip().lower() if hasattr(pred, 'answer') else ""
    
    # Safely extract the ground truth string
    ground_truth_intent = gold.answer.strip().lower()
    
    # Return a boolean score (True if match, False otherwise)
    return predicted_intent == ground_truth_intent

# 3. Initialize the GEPA Optimizer
gepa_optimizer = dspy.GEPA(
    metric=my_metric, 
    reflection_lm=reflection_model, 
    num_threads=10,
    auto="light" #Light, Medium, and Heavy modes control the aggressiveness of the optimizer's mutations. Light mode makes smaller, more conservative changes to the prompt, while Heavy mode makes larger, more radical changes. Medium mode strikes a balance between the two.
)

# 4. Compile and Optimize your Program
print("Starting GEPA Optimization...")

optimized_model = gepa_optimizer.compile(
    student=cot_predictor, 
    trainset=train_examples,
    valset=dev_examples
)

print("Optimization Complete!")

2026/06/06 04:54:48 INFO dspy.teleprompt.gepa.gepa: Running GEPA for approx 560 metric calls of the program. This amounts to 6.91 full evals on the train+val set.
2026/06/06 04:54:49 INFO dspy.teleprompt.gepa.gepa: Using 45 examples for tracking Pareto scores. You can consider using a smaller sample of the valset to allow GEPA to explore more diverse solutions within the same budget. GEPA requires you to provide the smallest valset that is just large enough to match your downstream task distribution, while providing as large trainset as possible.

Starting GEPA Optimization...

GEPA Optimization:   0%|          | 0/560 [00:00<?, ?rollouts/s]2026/06/06 04:54:49 INFO dspy.evaluate.evaluate: Average Metric: 13 / 45 (28.9%)
2026/06/06 04:54:49 INFO dspy.teleprompt.gepa.gepa: Iteration 0: Base program full valset score: 0.28888888888888886 over 45 / 45 examples
GEPA Optimization:   8%|▊         | 45/560 [00:00<00:01, 333.53rollouts/s]2026/06/06 04:54:49 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Selected program 0 score: 0.28888888888888886

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:00<00:00, 239.79it/s]

2026/06/06 04:54:49 INFO dspy.evaluate.evaluate: Average Metric: 0 / 3 (0.0%)

2026/06/06 04:55:31 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Proposed new text for predict: You are given:
- customer_message: a natural-language query about travel/transport.
- intent_labels: a single string containing all valid intent labels, separated by %.

Your task:
- Output exactly one predicted class as a single intent label.
- The output must be one label chosen verbatim from intent_labels.
- Do not output multiple labels, punctuation, explanations, or any text other than the single chosen label.

How to choose the label:
1) Match the user’s main intent to the most specific label available in intent_labels. If the user explicitly asks about two dimensions and a corresponding combined label exists (e.g., airfare+flight_time), choose the combined label. Otherwise, choose the single most specific label.

2) Use these domain mappings and synonyms (ATIS-style air travel domain):
- flight: requests to list/find flights or flight availability/schedules (e.g., “show me flights from X to Y [on DAY]”, “find flights”).
- airfare: price/cost of plane tickets (e.g., “how much is the ticket/fare/price”, “what does it cost”).
- flight_time: flight duration/travel time (e.g., “how long does it take”, “flight time”, “time en route”, “duration”).
- aircraft: aircraft/equipment type (e.g., “what kind of plane/equipment”).
- airport: airport names, codes, or info about airports (e.g., “DFW airport”, “which airport”).
- airline: carrier information (e.g., “which airline”, “what airline flies …”).
- distance: distance in miles/kilometers (e.g., “how far”, “distance between”).
- ground_service: non-price ground transport options to/from airports (e.g., “is there a shuttle/taxi/limousine/bus”, “what ground transportation is available”).
- ground_fare: price/cost of ground transportation (e.g., “how much is a taxi/limousine/shuttle”, “ground fare”).
- cheapest: explicitly seeking the lowest-price flight (e.g., “cheapest/lowest fare/lowest price flight”).
- quantity: counts (e.g., “how many flights/stops”).
- city: queries about cities served or city identification (rare).
- flight_no: requests involving specific flight numbers (e.g., “what is flight 123”, “give me the flight number”).
- capacity: seat capacity/number of seats.
- meal: meal availability on flights.
- restriction: fare/ticket restrictions (e.g., “Saturday night stay, change penalties, advance purchase”).
- abbreviation: expansions/meanings of abbreviations or codes (e.g., “what does DFW stand for”).
- flight+airfare: asking both to list flights and their prices.
- airfare+flight_time: asking both price and duration.
- airline+flight_no: linking airline and flight number (e.g., “which airline operates flight 123”).
- ground_service+ground_fare: asking both ground transport options and their prices.
- aircraft+flight+flight_no: aircraft type for a specific flight (or aircraft info tied to a particular listed flight/number).

3) Disambiguation rules:
- “how long does it take” → flight_time (do not choose distance unless “how far”, “miles”, or “distance” is explicitly asked).
- Mentions of price/cost/fare/“how much”:
  - For flights → airfare.
  - For ground transport (taxi/limousine/shuttle/bus) → ground_fare.
- Mentions of ground transport without price → ground_service.
- If both aspects are clearly requested and a combined label exists (e.g., airfare+flight_time, ground_service+ground_fare), choose the combined label.
- Day/time constraints (e.g., “Wednesday”, “in the morning”) do not change the intent; they still map to flight unless price/time/etc. is explicitly asked.

4) Formatting:
- Return only the single label, exactly as it appears in intent_labels (case and punctuation must match).
- Do not invent labels (e.g., “limousine” is invalid if not in intent_labels).

Examples (for guidance):
- “show me flights from denver to washington dc wednesday” → flight
- “how much is a limousine between dallas fort worth international airport and dallas” → ground_fare
- “how long does it take to get from denver to oakland” → flight_time
2026/06/06 04:56:14 INFO dspy.evaluate.evaluate: Average Metric: 1 / 3 (33.3%)
2026/06/06 04:56:14 INFO dspy.teleprompt.gepa.gepa: Iteration 1: New subsample score 1 is better than old score 0. Continue to full eval and add to candidate pool.
2026/06/06 05:00:55 INFO dspy.evaluate.evaluate: Average Metric: 23 / 45 (51.1%)
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Found a better program on the valset with score 0.5111111111111111.
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Valset score for new program: 0.5111111111111111 (coverage 45 / 45)
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Val aggregate for new program: 0.5111111111111111
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Individual valset scores for new program: {0: True, 1: True, 2: False, 3: False, 4: False, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: False, 16: True, 17: True, 18: False, 19: False, 20: True, 21: True, 22: False, 23: True, 24: True, 25: False, 26: False, 27: False, 28: False, 29: False, 30: False, 31: True, 32: False, 33: False, 34: False, 35: False, 36: True, 37: False, 38: False, 39: True, 40: True, 41: True, 42: False, 43: False, 44: True}
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: New valset pareto front scores: {0: True, 1: True, 2: False, 3: False, 4: False, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: False, 16: True, 17: True, 18: False, 19: False, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: False, 27: False, 28: False, 29: False, 30: False, 31: True, 32: False, 33: False, 34: False, 35: False, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: False, 43: False, 44: True}
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Valset pareto front aggregate score: 0.5777777777777777
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Updated valset pareto front programs: {0: {1}, 1: {0, 1}, 2: {0, 1}, 3: {0, 1}, 4: {0, 1}, 5: {1}, 6: {1}, 7: {0, 1}, 8: {1}, 9: {0, 1}, 10: {1}, 11: {0, 1}, 12: {0, 1}, 13: {1}, 14: {0, 1}, 15: {0, 1}, 16: {1}, 17: {0, 1}, 18: {0, 1}, 19: {0, 1}, 20: {1}, 21: {1}, 22: {0}, 23: {0, 1}, 24: {0, 1}, 25: {0, 1}, 26: {0, 1}, 27: {0, 1}, 28: {0, 1}, 29: {0, 1}, 30: {0, 1}, 31: {0, 1}, 32: {0, 1}, 33: {0, 1}, 34: {0, 1}, 35: {0, 1}, 36: {0, 1}, 37: {0}, 38: {0}, 39: {1}, 40: {1}, 41: {1}, 42: {0, 1}, 43: {0, 1}, 44: {1}}
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Best valset aggregate score so far: 0.5111111111111111
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Best program as per aggregate score on valset: 1
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Best score on valset: 0.5111111111111111
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Linear pareto front program index: 1
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 1: New program candidate index: 1
GEPA Optimization:  17%|█▋        | 96/560 [06:06<34:20,  4.44s/rollouts] 2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 2: No merge candidates found
2026/06/06 05:00:55 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Selected program 0 score: 0.28888888888888886

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:00<00:00, 40.40it/s]

2026/06/06 05:00:55 INFO dspy.evaluate.evaluate: Average Metric: 1 / 3 (33.3%)

2026/06/06 05:01:51 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Proposed new text for predict: You are given:
- customer_message: a natural-language query about air travel.
- intent_labels: a single line containing all possible labels for this task, delimited by % (percent signs).

Your task:
- Choose exactly one intent label from the provided intent_labels that best matches the customer_message.
- Output only that single label string, exactly as it appears in intent_labels (case and punctuation must match). Do not output any reasoning, explanations, extra words, punctuation, or multiple labels.

General selection rules:
- Always pick the most specific label that matches the user’s request.
- If the message clearly asks for two aspects and a combined label exists (labels joined with “+” such as flight+airfare or airfare+flight_time), use the combined label. If no appropriate combined label exists, pick the primary focus.
- Prefer labels indicating question type (e.g., quantity, abbreviation, cheapest) over generic topic labels (e.g., flight, airfare) when cues are present.

Label meanings and common cues:
- flight: Asking for flights/schedules/availability without specific emphasis on price or time. Cues: “show me flights”, “list flights”, “what flights …”
- flight_time: Departure/arrival times, durations, earliest/latest. Cues: “when”, “what time”, “arrival/departure time”, “duration”
- airfare: Price/fare amounts. Cues: “price”, “cost”, “fare”, “how much” (about flight price)
- aircraft: Aircraft type/equipment. Cues: “aircraft type”, “equipment”, “plane model”
- ground_service: Ground transportation to/from airports. Cues: “shuttle”, “limousine”, “taxi”, “rental car”, “ground transport”
- airport: Airport information or which airports serve a city/area. Cues: “airport(s) in/near”, “what airport serves …”
- airline: Airline carriers. Cues: “which airlines”, “what carriers”, “who flies …”
- distance: Distances between cities/airports. Cues: “distance”, “how far”
- abbreviation: Meaning/expansion of codes or abbreviations (including fare codes, airline codes). Cues: “what does X mean”, “what is X short for”, “code X meaning”
- ground_fare: Prices for ground transportation. Cues: “how much is the shuttle/taxi/limousine”, “ground fare”
- quantity: Counts or numbers of items. Cues: “how many”, “number of”. Example: “how many flights …” → quantity (even though it’s about flights).
- city: City listings/coverage. Cues: “what cities does [airline] serve/service”, “cities served”
- flight_no: Flight number(s). Cues: “what is the flight number”
- capacity: Seat or aircraft capacity/availability. Cues: “capacity”, “how many seats”
- flight+airfare: Asking for flights and their prices together. Cues: “list flights and fares”, “show flights with prices”
- meal: Meal service. Cues: “meals”, “meal served”
- restriction: Fare rules/limitations. Cues: “restrictions”, “refundable”, “change fees”, “advance purchase”, “Saturday night stay”
- airline+flight_no: Requests that jointly ask for the airline and flight number.
- ground_service+ground_fare: Ground transport plus its fare in one question.
- airfare+flight_time: Price in relation to specific times, or asking both fare and time together. Cues: “fare for the 7 pm flight”, “price and time”
- cheapest: Superlative price queries. Cues: “cheapest”, “lowest fare”, “least expensive”
- aircraft+flight+flight_no: Combined request including aircraft type, flight(s), and flight number(s).

Disambiguation tips:
- “How many …” always indicates quantity, even if the subject is flights, airlines, or cities. Example: “how many first class flights does united have leaving from all cities today” → quantity.
- “What cities does [airline] serve/service” asks for a list of cities → city.
- “What does the fare code F mean” asks for meaning of a code → abbreviation.
- “Cheapest” overrides airfare; choose cheapest when present.
- “How much” indicates airfare only if it’s about flight price. If it’s about ground transport price, use ground_fare.
- “Service/serve”:
  - If asking which cities an airline serves → city.
  - If asking which airlines serve a city/route → airline.
- Mentions of “today”, dates, or times alone do not force flight_time unless the question is specifically about times.

Output constraints:
- Return exactly one label from the provided intent_labels.
- Do not invent new labels or alter label text.
- Do not include any reasoning or extra text in the output.
2026/06/06 05:02:14 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:02:14 INFO dspy.teleprompt.gepa.gepa: Iteration 2: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
GEPA Optimization:  11%|█▏        | 63/560 [12:22<1:37:34, 11.78s/rollouts]
2026/06/06 05:06:12 INFO dspy.evaluate.evaluate: Average Metric: 22 / 45 (48.9%)
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Valset score for new program: 0.4888888888888889 (coverage 45 / 45)
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Val aggregate for new program: 0.4888888888888889
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Individual valset scores for new program: {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: True, 8: False, 9: False, 10: False, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: False, 18: False, 19: False, 20: False, 21: False, 22: True, 23: True, 24: True, 25: False, 26: True, 27: False, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: False, 36: True, 37: False, 38: True, 39: False, 40: True, 41: False, 42: True, 43: False, 44: False}
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: New valset pareto front scores: {0: True, 1: True, 2: False, 3: False, 4: False, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: False, 19: False, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: False, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: False, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: False, 44: True}
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Valset pareto front aggregate score: 0.7777777777777778
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Updated valset pareto front programs: {0: {1}, 1: {0, 1}, 2: {0, 1, 2}, 3: {0, 1, 2}, 4: {0, 1, 2}, 5: {1}, 6: {1}, 7: {0, 1, 2}, 8: {1}, 9: {0, 1, 2}, 10: {1}, 11: {0, 1, 2}, 12: {0, 1, 2}, 13: {1, 2}, 14: {0, 1, 2}, 15: {2}, 16: {1, 2}, 17: {0, 1}, 18: {0, 1, 2}, 19: {0, 1, 2}, 20: {1}, 21: {1}, 22: {0, 2}, 23: {0, 1, 2}, 24: {0, 1, 2}, 25: {0, 1, 2}, 26: {2}, 27: {0, 1, 2}, 28: {2}, 29: {2}, 30: {2}, 31: {0, 1, 2}, 32: {2}, 33: {2}, 34: {2}, 35: {0, 1, 2}, 36: {0, 1, 2}, 37: {0}, 38: {0, 2}, 39: {1}, 40: {1, 2}, 41: {1}, 42: {2}, 43: {0, 1, 2}, 44: {1}}
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Best valset aggregate score so far: 0.5111111111111111
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Best program as per aggregate score on valset: 1
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Best score on valset: 0.5111111111111111
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Linear pareto front program index: 1
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 2: New program candidate index: 2
GEPA Optimization:  26%|██▋       | 147/560 [11:23<36:18,  5.28s/rollouts]2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 3: No merge candidates found
2026/06/06 05:06:12 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Selected program 2 score: 0.4888888888888889

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:12<00:00,  4.26s/it]

2026/06/06 05:06:25 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)

2026/06/06 05:07:37 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Proposed new text for predict: You are classifying a single natural-language air travel query into exactly one intent label.

Inputs you will receive:
- customer_message: a free-form query about air travel.
- intent_labels: a single line listing all possible labels for this task, delimited by %.

Your output:
- Return exactly one label string, exactly matching one of the labels provided in intent_labels (case and punctuation must match).
- Output only the label. Do not include explanations, reasoning, extra words, punctuation, or multiple labels.
- No surrounding quotes, no leading/trailing spaces or newlines beyond the single line with the label.

Core strategy:
1) Identify what information the user is explicitly asking to receive (the requested output), not the filters/constraints they provide (e.g., cities, dates, times, airlines often act as constraints).
2) Look for high-priority cues that determine specific labels (e.g., “how many”, “cheapest”, “what does X mean”).
3) If the user clearly asks for two aspects and a combined label exists (labels joined with “+”), choose that combined label.
4) If multiple aspects are asked but no appropriate combined label exists, choose the primary focus (the main thing the user asks to be listed/returned). Treat dates/times/cities/airlines as constraints unless the question is specifically about those as outputs.
5) Prefer question-type/specific labels over generic topic labels when cues indicate them (e.g., quantity over flight).

Label meanings with cues (include synonyms/phrases):
- flight: Requests for flights/schedules/availability without special emphasis on price or specific times. Cues: “show/list flights”, “what flights”, “schedule(s)”, “nonstop vs connecting”, “availability”.
- flight_time: Specific departure/arrival times, durations, earliest/latest, time-of-day constraints as the asked output. Cues: “when”, “what time”, “arrival/departure time”, “arrive by/before/after”, “duration”, “earliest/latest flight”.
- airfare: Flight prices/fares. Cues: “price”, “cost”, “fare”, “how much” (about flight price), “ticket price/rate”.
- aircraft: Aircraft type/equipment/plane model. Cues: “aircraft type”, “equipment”, “plane/jet model”, “Boeing/Airbus used”.
- ground_service: Ground transportation to/from airports. Cues: “shuttle”, “taxi”, “bus”, “limousine”, “rental car”, “train to the airport”.
- airport: Airport info or which airports serve a city/area. Cues: “airport(s) in/near”, “which airport serves…”, “closest airport”.
- airline: Airline carriers serving a route/city. Cues: “which airlines”, “what carriers”, “who flies …”.
- distance: Distances between cities/airports. Cues: “distance”, “how far”, “miles/kilometers between”.
- abbreviation: Meaning/expansion of codes/abbreviations (airport/airline/fare codes). Cues: “what does X mean”, “what is X short for”, “code X meaning”.
- ground_fare: Prices for ground transportation. Cues: “how much is the shuttle/taxi/limousine”, “ground fare”, “bus fare”.
- quantity: Counts or numbers of items. Cues: “how many”, “number of”, “count of”. Applies regardless of subject (flights, airlines, cities, etc.).
- city: City listings/coverage by an airline. Cues: “what cities does [airline] serve/service”, “cities served”, “destinations”.
- flight_no: Flight number(s). Cues: “what is the flight number”, “flight no.”, “number of the flight”.
- capacity: Seat/aircraft capacity or seat availability. Cues: “capacity”, “how many seats”, “seats available/left”, “seat availability”.
- flight+airfare: Asking for flights and their prices together. Cues: “list/show flights with prices/fares”.
- meal: Meal service. Cues: “meals”, “meal served”, “food/snack/breakfast/lunch/dinner on the flight”.
- restriction: Fare rules/limitations. Cues: “restrictions”, “refundable”, “nonrefundable”, “change fees”, “advance purchase”, “Saturday night stay”, “penalties”, “blackout dates”.
- airline+flight_no: Jointly asking for the airline(s) and the flight number(s). Cues: “airlines and flight numbers”.
- ground_service+ground_fare: Ground transport plus its fare together. Cues: “shuttle and its price”, “taxi options and cost”.
- airfare+flight_time: Fare in relation to specific times, or jointly asking price and time. Cues: “fare for the 7 pm flight”, “price and time”, “cost of the evening/morning flight”.
- cheapest: Superlative/lowest price queries. Cues: “cheapest”, “lowest fare”, “least expensive”.
- aircraft+flight+flight_no: Combined request including aircraft type, flight(s), and flight number(s) together.

Priority and disambiguation rules:
- “How many …” → quantity (even if about flights/airlines/cities).
- “Cheapest/lowest/least expensive” → cheapest (overrides airfare).
- “What does/code/meaning/stand for” → abbreviation (for airport/airline/fare codes).
- “How much”:
  - If about flight price → airfare.
  - If about ground transport price → ground_fare.
- “Service/serve”:
  - If asking which cities an airline serves → city.
  - If asking which airlines serve a city/route → airline.
- Mentions of dates/times or time filters alone do not force flight_time unless the time itself is the requested output. Time constraints that filter other requested info do not change the label.
  - Example: “airlines and flight numbers … arriving before noon” → airline+flight_no (time is a filter, not the requested output).
- Combined labels take precedence when explicitly asking for exactly those combined aspects.
  - Example: “airlines and flight numbers” → airline+flight_no.
  - Example: “flights with prices” → flight+airfare.
  - Example: “price and time” or “fare for the 7 pm flight” → airfare+flight_time.
- City/airline/airport names, dates, and times generally act as filters/context unless explicitly asked for as the information to return.
- “Schedule(s)” maps to flight unless the question explicitly asks for exact times (then consider flight_time).

Execution checklist for each query:
1) Extract the exact information the user wants returned.
2) Check for high-priority cues (quantity, cheapest, abbreviation, how much).
3) If two aspects are clearly requested and a matching combined label exists, use it.
4) Otherwise choose the most specific single label matching the requested information; treat time/date/city/airline mentions as filters.
5) Output only the exact matching label from intent_labels.

Examples aligned with these rules:
- “may i please see airlines and flight numbers … arriving … before noon” → airline+flight_no.
- “what are all the available meals” → meal.
- “what kind of airplanes are used by delta …” → aircraft.
2026/06/06 05:08:09 INFO dspy.evaluate.evaluate: Average Metric: 3 / 3 (100.0%)
2026/06/06 05:08:09 INFO dspy.teleprompt.gepa.gepa: Iteration 3: New subsample score 3 is better than old score 2. Continue to full eval and add to candidate pool.
2026/06/06 05:13:17 INFO dspy.evaluate.evaluate: Average Metric: 27 / 45 (60.0%)
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Found a better program on the valset with score 0.6.
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Valset score for new program: 0.6 (coverage 45 / 45)
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Val aggregate for new program: 0.6
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Individual valset scores for new program: {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: False, 9: False, 10: False, 11: True, 12: False, 13: False, 14: True, 15: False, 16: False, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: False, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: False}
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: New valset pareto front scores: {0: True, 1: True, 2: False, 3: False, 4: False, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Valset pareto front aggregate score: 0.8888888888888888
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Updated valset pareto front programs: {0: {1}, 1: {0, 1}, 2: {0, 1, 2, 3}, 3: {0, 1, 2, 3}, 4: {0, 1, 2, 3}, 5: {1}, 6: {1}, 7: {0, 1, 2}, 8: {1}, 9: {0, 1, 2, 3}, 10: {1}, 11: {0, 1, 2, 3}, 12: {0, 1, 2}, 13: {1, 2}, 14: {0, 1, 2, 3}, 15: {2}, 16: {1, 2}, 17: {0, 1, 3}, 18: {3}, 19: {3}, 20: {1, 3}, 21: {1, 3}, 22: {0, 2, 3}, 23: {0, 1, 2, 3}, 24: {0, 1, 2, 3}, 25: {0, 1, 2, 3}, 26: {2, 3}, 27: {3}, 28: {2, 3}, 29: {2, 3}, 30: {2, 3}, 31: {0, 1, 2, 3}, 32: {2, 3}, 33: {2, 3}, 34: {2, 3}, 35: {3}, 36: {0, 1, 2, 3}, 37: {0}, 38: {0, 2, 3}, 39: {1, 3}, 40: {1, 2, 3}, 41: {1, 3}, 42: {2, 3}, 43: {3}, 44: {1}}
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Best valset aggregate score so far: 0.6
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Best program as per aggregate score on valset: 3
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Best score on valset: 0.6
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Linear pareto front program index: 3
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 3: New program candidate index: 3
GEPA Optimization:  35%|███▌      | 198/560 [18:28<39:13,  6.50s/rollouts]2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 4: No merge candidates found
2026/06/06 05:13:17 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Selected program 1 score: 0.5111111111111111

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:23<00:00,  7.67s/it]

2026/06/06 05:13:40 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)

2026/06/06 05:14:47 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Proposed new text for predict: You are a single-label intent classifier for travel/transportation queries (ATIS-style). You will be given:
- customer_message: a natural-language query.
- intent_labels: a single string containing all valid intent labels, separated by %.

Your job:
- Output exactly one label, chosen verbatim from intent_labels.
- Output only the single label (no extra text, punctuation, or explanations).

General selection strategy:
1) Identify the user’s main intent from the message.
2) Choose the most specific matching label available in intent_labels.
3) If the user clearly asks about two dimensions and a corresponding combined label exists, choose the combined label (e.g., flight+airfare, airfare+flight_time, ground_service+ground_fare, airline+flight_no, aircraft+flight+flight_no). If no combined label exists, choose the single most specific label.
4) Ignore constraints like trip type (round-trip/one-way), day, date, or time-of-day when selecting the intent; they don’t change the intent category.

Domain mappings and synonyms (use these triggers):
- flight: list/find flights or schedules/availability (e.g., “show/find/list flights”, “what flights go from X to Y [when]”, “are there flights”).
- airfare: price/cost of plane tickets (e.g., “fare”, “price”, “how much is the ticket/flight”).
- flight_time: flight duration/travel time (e.g., “how long does it take”, “duration”, “time en route”).
- aircraft: aircraft/equipment type (e.g., “what kind of plane”, “equipment type”).
- airport: airport names, codes, or info about airports (e.g., “airports in/near X”, “DFW airport/code”).
- airline: carrier information (e.g., “which airline(s)”, “what airlines fly/serve …”, “which carrier(s) operate …”). Important: If the question is specifically about which airline(s) operate/serve a route, choose airline (not flight).
- distance: distance in miles/kilometers (e.g., “how far”, “distance between”).
- ground_service: non-price ground transport to/from airports (e.g., “is there a shuttle/taxi/limousine/bus”, “what ground transportation is available”).
- ground_fare: price/cost of ground transportation (e.g., “how much is a taxi/limousine/shuttle/bus”).
- cheapest: explicitly seeking the lowest-price flight (e.g., “cheapest/lowest fare/lowest price flight”). If cheapest is not present in intent_labels, fall back to airfare.
- quantity: counts (e.g., “how many flights”, “how many stops”).
- city: city identification/coverage (e.g., “what cities are served”, “what city is X in”).
- flight_no: intent centered on flight numbers (e.g., “what is flight 123”, “give me the flight number”, “about flight 123”).
- capacity: seat capacity/number of seats (e.g., “how many seats”).
- meal: meal availability on flights (e.g., “is there a meal/food service”).
- restriction: fare/ticket restrictions (e.g., “Saturday night stay”, “advance purchase”, “change penalties”).
- abbreviation: meanings/expansions of codes/abbreviations (e.g., “what does DFW stand for”).

Combined labels (choose these when both aspects are clearly asked and the combined label exists in intent_labels):
- flight+airfare: asking to list flights and their prices together (e.g., “show flights from X to Y with prices”).
- airfare+flight_time: asking both ticket price and duration (e.g., “how much and how long”).
- airline+flight_no: linking an airline with a specific flight number (e.g., “which airline operates flight 123”).
- ground_service+ground_fare: asking both ground transportation options and their prices.
- aircraft+flight+flight_no: aircraft type tied to a specific flight/number (e.g., “what aircraft operates flight 123”).

Disambiguation rules:
- “how long does it take” → flight_time (do not choose distance unless “how far”, “miles”, or “distance” is explicitly asked).
- Mentions of price/cost/fare/“how much”:
  - For flights → airfare (or cheapest if explicitly seeking the lowest-price flight and cheapest is available).
  - For ground transport → ground_fare.
- Mentions of ground transport without price → ground_service.
- If both aspects are clearly requested and a combined label exists, select the combined label; otherwise pick the single most specific label.
- Route, date, time-of-day, and trip-type details do not change the core intent (e.g., still “flight” unless the user explicitly asks about price, duration, airline, etc.).

Edge cues and examples to avoid common mistakes:
- “what airlines fly from boston to atlanta” → airline (not flight).
- “please show me all airports in denver” → airport.
- “how long does it take to get from denver to oakland” → flight_time.
- “show me the lowest fare for a round trip flight from baltimore to dallas” → cheapest (if available), otherwise airfare.

Formatting:
- Return only one label from intent_labels, exactly matching its case/spelling.
- Do not add any other text, punctuation, or whitespace beyond the label.
2026/06/06 05:15:13 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:15:14 INFO dspy.teleprompt.gepa.gepa: Iteration 4: New subsample score 2 is not better than old score 2, skipping
GEPA Optimization:  36%|███▋      | 204/560 [20:24<43:24,  7.32s/rollouts]2026/06/06 05:15:14 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Selected program 0 score: 0.28888888888888886

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:00<00:00, 124.21it/s]

2026/06/06 05:15:14 INFO dspy.evaluate.evaluate: Average Metric: 0 / 3 (0.0%)

2026/06/06 05:16:12 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Proposed new text for predict: Task
- You will receive:
  - customer_message: a natural-language query about air travel
  - intent_labels: the complete, allowed set of intent labels, delimited by the % character
- Your job is to output exactly one label from intent_labels that best matches the customer_message.
- Output must be the single label string only (no explanations, no extra text, no multiple labels, no delimiters).

General rules
- Select exactly one label that appears verbatim in intent_labels.
- Prefer the most specific label that directly matches the explicit request.
- If the user asks for multiple pieces of information and a matching combined label exists (labels joined with +), output that single combined label (e.g., flight+airfare for “flights and fares”).
- Do not output multiple separate labels. If no exact combined label covers all requested info, choose the single label that best captures the main asked-for information.
- Cities, dates, and other details do not change the intent; they only provide context.
- Use labels exactly as given (lowercase, with + or underscores as shown). Do not add %, spaces, or punctuation.

Label selection guide (keywords/synonyms)
- flight: requests to list/show/find flights, availability, or schedules without explicit emphasis on times (e.g., “what flights from X to Y”, “list flights”).
- flight_no: explicit request for flight numbers or a “listing of flight numbers”.
- flight_time: requests about departure/arrival times, duration, or schedule times (e.g., “what time”, “when does it arrive/depart”, “how long”).
- airfare: requests about fare/price/cost/rate for air travel (e.g., “fares”, “prices”, “how much”).
- cheapest: explicit request for the lowest fare or cheapest option (e.g., “cheapest flight”, “lowest fare”).
- flight+airfare: simultaneous request for flights and fares (e.g., “show flights and fares”).
- airfare+flight_time: simultaneous request for fare and time information (e.g., “price and time”, “fare and schedule times”).
- airline: requests about airlines/carriers (e.g., “which airlines serve this route”, “what airline operates…”).
- airline+flight_no: requests that explicitly ask for both the airline and the flight number.
- aircraft: requests about aircraft type/equipment/plane model.
- aircraft+flight+flight_no: requests that jointly ask for aircraft type along with flights and their numbers.
- airport: requests about airports (e.g., “which airport in city X”, “airports serving X”).
- city: mapping between airport/airline codes and cities, or questions asking which city an airport/code is in.
- abbreviation: requests for codes or expansions of codes (e.g., “what is the code/abbreviation for…”, “what does DFW stand for”).
- distance: distance/miles between cities or airports.
- ground_service: ground transportation/services at or to/from airports (e.g., shuttle, bus, limo).
- ground_fare: price/cost for ground transportation.
- ground_service+ground_fare: simultaneous request for ground services and their prices.
- quantity: number of flights or counts (e.g., “how many flights”).
- capacity: seat capacity or how many seats are available on an aircraft/flight.
- meal: meal/food service availability on flights.
- restriction: fare or booking restrictions (e.g., advance purchase, Saturday-night stay, refundability).

Disambiguation tips
- “What flights …” -> flight (do not add airfare/cheapest unless explicitly requested).
- “Listing of flight numbers …” -> flight_no.
- “Show all flights and fares …” -> flight+airfare.
- If a time component is emphasized (“what time/when/how long”), choose flight_time or airfare+flight_time if prices are also asked.
- If the user mentions multiple info types but no exact combined label exists, pick the single most central intent (often flight, or the most explicit specific one like flight_no).

Output format
- Return only the single chosen label string exactly as it appears in intent_labels.
2026/06/06 05:16:42 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:16:42 INFO dspy.teleprompt.gepa.gepa: Iteration 5: New subsample score 2 is better than old score 0. Continue to full eval and add to candidate pool.
2026/06/06 05:20:20 INFO dspy.evaluate.evaluate: Average Metric: 23 / 45 (51.1%)
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Valset score for new program: 0.5111111111111111 (coverage 45 / 45)
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Val aggregate for new program: 0.5111111111111111
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Individual valset scores for new program: {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: True, 8: False, 9: False, 10: False, 11: True, 12: False, 13: False, 14: True, 15: False, 16: True, 17: True, 18: False, 19: False, 20: True, 21: True, 22: True, 23: True, 24: False, 25: False, 26: False, 27: False, 28: False, 29: False, 30: False, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: New valset pareto front scores: {0: True, 1: True, 2: False, 3: False, 4: False, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Valset pareto front aggregate score: 0.8888888888888888
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Updated valset pareto front programs: {0: {1}, 1: {0, 1}, 2: {0, 1, 2, 3, 4}, 3: {0, 1, 2, 3, 4}, 4: {0, 1, 2, 3, 4}, 5: {1}, 6: {1}, 7: {0, 1, 2, 4}, 8: {1}, 9: {0, 1, 2, 3, 4}, 10: {1}, 11: {0, 1, 2, 3, 4}, 12: {0, 1, 2}, 13: {1, 2}, 14: {0, 1, 2, 3, 4}, 15: {2}, 16: {1, 2, 4}, 17: {0, 1, 3, 4}, 18: {3}, 19: {3}, 20: {1, 3, 4}, 21: {1, 3, 4}, 22: {0, 2, 3, 4}, 23: {0, 1, 2, 3, 4}, 24: {0, 1, 2, 3}, 25: {0, 1, 2, 3, 4}, 26: {2, 3}, 27: {3}, 28: {2, 3}, 29: {2, 3}, 30: {2, 3}, 31: {0, 1, 2, 3, 4}, 32: {2, 3, 4}, 33: {2, 3, 4}, 34: {2, 3, 4}, 35: {3, 4}, 36: {0, 1, 2, 3, 4}, 37: {0, 4}, 38: {0, 2, 3, 4}, 39: {1, 3, 4}, 40: {1, 2, 3, 4}, 41: {1, 3, 4}, 42: {2, 3, 4}, 43: {3, 4}, 44: {1, 4}}
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Best valset aggregate score so far: 0.6
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Best program as per aggregate score on valset: 3
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Best score on valset: 0.6
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Linear pareto front program index: 3
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 5: New program candidate index: 4
GEPA Optimization:  46%|████▌     | 255/560 [25:31<34:17,  6.75s/rollouts]2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 6: No merge candidates found
2026/06/06 05:20:20 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Selected program 2 score: 0.4888888888888889

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:41<00:00, 13.77s/it]

2026/06/06 05:21:01 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)

2026/06/06 05:21:48 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Proposed new text for predict: You are performing single-label intent classification for natural-language air travel queries.

Inputs:
- customer_message: a user’s question about air travel.
- intent_labels: a single line listing all allowed labels, delimited by %.

Your output:
- Return exactly one label from intent_labels.
- Output only the label string, exactly as it appears (case and punctuation must match).
- Do not output explanations, extra words, punctuation, or multiple labels.

Core selection principles:
- Always choose the most specific label that matches the user’s request.
- Prefer question-type labels (e.g., quantity, abbreviation, cheapest, flight_time) over generic topic labels (e.g., flight, airfare) when cues are present.
- Use a combined label (e.g., flight+airfare, airfare+flight_time, ground_service+ground_fare, airline+flight_no, aircraft+flight+flight_no) only when the user explicitly asks for all aspects in that combined label. Do not select a combined label merely because multiple concepts are mentioned; they must be directly requested.

Decision procedure (apply in order):
1) Detect unambiguous question-type cues:
   - “how many”, “number of” → quantity (regardless of subject: flights, airlines, cities, etc.).
   - “cheapest”, “lowest fare”, “least expensive” → cheapest (overrides airfare).
   - Code meaning requests (“what does X mean”, “what is X short for”, “code X meaning”, fare code/airline code/airport code expansions) → abbreviation.
   - Time-focused queries: “when”, “what time”, “arrival/arrive”, “departure/depart”, “duration”, “earliest”, “latest” → flight_time.
   - Price-focused queries for air travel: “price”, “cost”, “fare”, “how much” (re flights) → airfare.
   - Price-focused queries for ground transport: “how much is the taxi/shuttle/limousine/bus”, “ground fare” → ground_fare.
2) If none of the above apply, map to topical labels:
   - flight: listing/availability/schedules without emphasis on price or time. Cues: “show/list/find flights”, “what flights…”, “schedules”.
   - airline: which carriers operate a route/serve a place. Cues: “which airlines”, “what carriers”, “who flies…”.
   - city: list of cities served by an airline. Cues: “what cities does [airline] serve/service”.
   - airport: airport information or which airports serve a city/area. Cues: “airport(s) in/near”, “what airport serves…”.
   - ground_service: ground transportation options. Cues: “shuttle”, “limousine”, “taxi”, “rental car”, “ground transport”.
   - distance: “distance”, “how far”, miles/kilometers between cities/airports.
   - aircraft: aircraft type/equipment. Cues: “aircraft type”, “equipment”, “plane model”.
   - flight_no: asking for flight number(s). Cues: “what is the flight number”.
   - capacity: seat/aircraft capacity/availability. Cues: “capacity”, “how many seats”.
   - meal: meals/meal service. Cues: “meals”, “meal served”.
   - restriction: fare rules/limitations. Cues: “restrictions”, “refundable”, “change fees”, “advance purchase”, “Saturday night stay”.
3) Use combined labels only when all components are explicitly requested:
   - flight+airfare: asks for flights and their prices together. Cues: “list/show flights with prices/fares”.
   - airfare+flight_time: asks for both fare and time, or price tied to a specific time/flight. Cues: “price and time”, “fare for the 7 pm flight”.
   - ground_service+ground_fare: asks about ground transport and its price together.
   - airline+flight_no: explicitly requests both airline and flight number together.
   - aircraft+flight+flight_no: explicitly requests aircraft type, flight(s), and flight number(s) together.
   Do not select these combined labels if only one aspect is asked.
4) Disambiguation tips:
   - “How many …” → quantity, even if about flights/airlines/cities.
   - “Service/serve”:
     • “What cities does [airline] serve/service” → city.
     • “Which airlines serve [city/route]” → airline.
   - Mentions of dates/times (e.g., “today”, “Tuesday morning”) or flight numbers alone do not force a combined label. Choose flight_time only if the question is specifically about time (arrival/departure/duration).
   - Mentioning a flight number does not imply flight_no unless the user asks for the flight number itself.
   - “How much” → airfare only when clearly about flight price; if about taxi/shuttle/ground transport price → ground_fare.
   - Cheapest overrides airfare.
   - If two aspects are mentioned but only one is explicitly requested, choose the requested aspect (do not infer a combined label).

Examples reflecting correct choices:
- “show me city served both by nationair and canadian airlines international” → city.
- “ground transportation in las vegas” → ground_service.
- “what time does the tuesday morning 755 flight leaving washington arrive in san francisco” → flight_time (time-focused; presence of a flight number does not make it a combined label).
- “list flights and fares from boston to chicago” → flight+airfare.
- “what is the cheapest ticket from la to nyc next weekend” → cheapest.
- “how much is the shuttle from the airport to downtown” → ground_fare.
- “what does the fare code F mean” → abbreviation.
- “which airlines fly from denver to miami” → airline.
- “how many flights does united have today” → quantity.
- “what airports serve the san francisco bay area” → airport.
- “what aircraft operates aa 100” → aircraft.
- “what is the flight number for the 7 pm delta flight to atlanta” → flight_no (if only the number is requested); airline+flight_no only if both airline and flight number are explicitly requested.

Output constraint reminder:
- Return exactly one label from intent_labels, with exact text match, and nothing else.
2026/06/06 05:22:03 INFO dspy.evaluate.evaluate: Average Metric: 3 / 3 (100.0%)
2026/06/06 05:22:03 INFO dspy.teleprompt.gepa.gepa: Iteration 6: New subsample score 3 is better than old score 2. Continue to full eval and add to candidate pool.
2026/06/06 05:24:42 INFO dspy.evaluate.evaluate: Average Metric: 26 / 45 (57.8%)
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Valset score for new program: 0.5777777777777777 (coverage 45 / 45)
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Val aggregate for new program: 0.5777777777777777
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Individual valset scores for new program: {0: True, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: True, 8: False, 9: False, 10: False, 11: True, 12: True, 13: False, 14: True, 15: False, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: False, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: False, 33: False, 34: True, 35: False, 36: True, 37: False, 38: True, 39: True, 40: True, 41: True, 42: False, 43: False, 44: True}
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: New valset pareto front scores: {0: True, 1: True, 2: False, 3: False, 4: False, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Valset pareto front aggregate score: 0.8888888888888888
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Updated valset pareto front programs: {0: {1, 5}, 1: {0, 1}, 2: {0, 1, 2, 3, 4, 5}, 3: {0, 1, 2, 3, 4, 5}, 4: {0, 1, 2, 3, 4, 5}, 5: {1}, 6: {1}, 7: {0, 1, 2, 4, 5}, 8: {1}, 9: {0, 1, 2, 3, 4, 5}, 10: {1}, 11: {0, 1, 2, 3, 4, 5}, 12: {0, 1, 2, 5}, 13: {1, 2}, 14: {0, 1, 2, 3, 4, 5}, 15: {2}, 16: {1, 2, 4, 5}, 17: {0, 1, 3, 4, 5}, 18: {3, 5}, 19: {3, 5}, 20: {1, 3, 4, 5}, 21: {1, 3, 4, 5}, 22: {0, 2, 3, 4, 5}, 23: {0, 1, 2, 3, 4, 5}, 24: {0, 1, 2, 3}, 25: {0, 1, 2, 3, 4, 5}, 26: {2, 3, 5}, 27: {3, 5}, 28: {2, 3, 5}, 29: {2, 3, 5}, 30: {2, 3, 5}, 31: {0, 1, 2, 3, 4, 5}, 32: {2, 3, 4}, 33: {2, 3, 4}, 34: {2, 3, 4, 5}, 35: {3, 4}, 36: {0, 1, 2, 3, 4, 5}, 37: {0, 4}, 38: {0, 2, 3, 4, 5}, 39: {1, 3, 4, 5}, 40: {1, 2, 3, 4, 5}, 41: {1, 3, 4, 5}, 42: {2, 3, 4}, 43: {3, 4}, 44: {1, 4, 5}}
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Best valset aggregate score so far: 0.6
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Best program as per aggregate score on valset: 3
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Best score on valset: 0.6
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Linear pareto front program index: 3
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 6: New program candidate index: 5
GEPA Optimization:  55%|█████▍    | 306/560 [29:53<25:58,  6.14s/rollouts]2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 7: No merge candidates found
2026/06/06 05:24:42 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Selected program 3 score: 0.6

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:13<00:00,  4.56s/it]

2026/06/06 05:24:56 INFO dspy.evaluate.evaluate: Average Metric: 1 / 3 (33.3%)

2026/06/06 05:26:19 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Proposed new text for predict: You classify a single natural-language air travel query into exactly one intent label from a provided list.

Inputs you will receive:
- customer_message: a free-form query about air travel.
- intent_labels: a single line listing all possible labels for this task, delimited by %.

Your output:
- Return exactly one label string that exactly matches one of the labels in intent_labels (case and punctuation must match).
- Output only the label on a single line. No explanations, no extra words, no punctuation, no quotes, and no leading/trailing spaces or blank lines.

Core strategy (what to return vs. what are filters):
1) Identify the specific type of information the user wants returned (the requested output).
2) Treat cities, dates, times, airlines, cabins/classes (e.g., first class), trip type (one-way/round-trip), and similar details as filters unless the user is explicitly asking for those as the output.
3) Prefer more specific, question-type labels over generic topic labels when clear cues exist.
4) If two distinct aspects are clearly requested and an exact combined label exists (labels joined with “+”), select that combined label. Otherwise pick the single most specific label that matches the requested output.

High-priority cues and disambiguation:
- How many:
  - If the counted noun is “seats” (or clearly about seat availability/capacity), use capacity.
  - Otherwise (flights, airlines, cities, airports, etc.), use quantity.
- Cheapest/lowest/least expensive:
  - Use airfare when the user asks for the cheapest/lowest fare/price/cost (e.g., “cheapest one way fare”).
  - Use cheapest only when the user’s goal is to identify the cheapest flight/itinerary option as such (e.g., “the cheapest flight”), not just to obtain a fare amount.
- How much:
  - About flight price/ticket/fare → airfare.
  - About ground transport price (taxi/shuttle/bus/limousine/train) → ground_fare.
- What does/meaning/stand for/code → abbreviation (airport/airline/fare codes).
- Service/serve:
  - “What cities does [airline] serve” → city.
  - “Which airlines serve [city/route]” → airline.
- Time mentions:
  - Times/dates typically act as filters. Only use flight_time when exact times/durations/earliest/latest are the requested output.
- “Schedule(s)” maps to flight unless exact times are the information requested (then flight_time).

Label glossary with key cues:
- flight: Listing/availability/schedules of flights without focusing on prices or specific times. Cues: “show/list flights”, “schedules”, “availability”.
- flight_time: Exact departure/arrival times, durations, earliest/latest, arrive by/before/after as the asked output. Cues: “when”, “what time”, “duration”.
- airfare: Prices/fares for flights. Cues: “price”, “cost”, “fare”, “how much” (re flight price), “cheapest/lowest fare” when asking for a fare amount.
- aircraft: Aircraft type/equipment/model. Cues: “aircraft type”, “equipment”, “plane/jet model”, “Boeing/Airbus used”.
- ground_service: Ground transportation to/from airports. Cues: “shuttle”, “taxi”, “bus”, “limousine”, “rental car”, “train”.
- airport: Airport info or which airports serve a city/area. Cues: “airport(s) in/near”, “which airport serves…”, “closest airport”.
- airline: Airlines serving a route/city. Cues: “which airlines”, “what carriers”, “who flies …”.
- distance: Distances between cities/airports. Cues: “distance”, “how far”, “miles/kilometers”.
- abbreviation: Meaning/expansion of codes. Cues: “what does X mean”, “what is X short for”.
- ground_fare: Prices for ground transportation. Cues: “how much is the shuttle/taxi/limousine”, “bus fare”.
- quantity: Counts/numbers (not seats). Cues: “how many”, “number of”, “count of” for flights/airlines/cities/airports/etc.
- city: City lists/coverage by an airline. Cues: “what cities does [airline] serve”.
- flight_no: Flight number(s). Cues: “what is the flight number”, “flight no.”.
- capacity: Seat/aircraft capacity or seat availability. Cues: “capacity”, “how many seats”, “seats available/left”.
- flight+airfare: Jointly requesting flights with their prices. Cues: “flights with prices/fares”.
- meal: Meal service. Cues: “meals”, “food/snack/breakfast/lunch/dinner on the flight”.
- restriction: Fare rules/limitations. Cues: “restrictions”, “refundable/nonrefundable”, “change fees”, “advance purchase”, “Saturday night stay”, “penalties”, “blackout dates”.
- airline+flight_no: Asking for both airlines and flight numbers together.
- ground_service+ground_fare: Ground transport options plus their prices together.
- airfare+flight_time: Price in relation to specific times, or jointly asking price and time. Cues: “fare for the 7 pm flight”, “price and time”.
- cheapest: Use only when the user’s primary output is “the cheapest flight/itinerary” itself (identify the cheapest option), not merely a fare amount.
- aircraft+flight+flight_no: Combined request including aircraft type, flight(s), and flight number(s).

Important domain notes:
- Mentions like first class/business class, nonstop/connection preference, one-way/round-trip are filters unless explicitly the requested output.
- Example: “how many cities are served by TWA with first class flights” → quantity (count of cities); “TWA” and “first class” are filters.
- Example: “how many seats in a 100” → capacity (seats imply capacity).
- Example: “cheapest one way fare from boston to philadelphia” → airfare (asking for a fare amount even though “cheapest” is used).

Combined labels:
- Use combined labels only when the query explicitly requests exactly those combined aspects together (e.g., “airlines and flight numbers”, “flights with prices”, “fare for the 7 pm flight”).
- The presence of times/dates alone does not force a combined label unless both aspects are being requested.

Execution checklist:
1) Identify the exact information requested as output (not filters).
2) Apply high-priority cues and exceptions:
   - “how many seats” → capacity.
   - Other “how many …” → quantity.
   - “cheapest/lowest … fare/price” → airfare.
   - “what does/meaning/code” → abbreviation.
3) If two aspects are explicitly requested and a matching combined label exists, use it; otherwise choose the single most specific label.
4) Output only the exact matching label string from intent_labels.

Formatting:
- Output exactly one label on a single line. No reasoning, no extra characters, no blanks before/after.
2026/06/06 05:26:31 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:26:31 INFO dspy.teleprompt.gepa.gepa: Iteration 7: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
2026/06/06 05:28:26 INFO dspy.evaluate.evaluate: Average Metric: 24 / 45 (53.3%)
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Valset score for new program: 0.5333333333333333 (coverage 45 / 45)
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Val aggregate for new program: 0.5333333333333333
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Individual valset scores for new program: {0: True, 1: True, 2: True, 3: False, 4: True, 5: True, 6: False, 7: True, 8: False, 9: False, 10: True, 11: False, 12: False, 13: False, 14: True, 15: True, 16: False, 17: True, 18: True, 19: True, 20: True, 21: True, 22: False, 23: False, 24: False, 25: False, 26: True, 27: False, 28: True, 29: False, 30: True, 31: True, 32: False, 33: True, 34: False, 35: True, 36: True, 37: False, 38: True, 39: True, 40: True, 41: False, 42: False, 43: False, 44: False}
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: New valset pareto front scores: {0: True, 1: True, 2: True, 3: False, 4: True, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Valset pareto front aggregate score: 0.9333333333333333
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Updated valset pareto front programs: {0: {1, 5, 6}, 1: {0, 1, 6}, 2: {6}, 3: {0, 1, 2, 3, 4, 5, 6}, 4: {6}, 5: {1, 6}, 6: {1}, 7: {0, 1, 2, 4, 5, 6}, 8: {1}, 9: {0, 1, 2, 3, 4, 5, 6}, 10: {1, 6}, 11: {0, 1, 2, 3, 4, 5}, 12: {0, 1, 2, 5}, 13: {1, 2}, 14: {0, 1, 2, 3, 4, 5, 6}, 15: {2, 6}, 16: {1, 2, 4, 5}, 17: {0, 1, 3, 4, 5, 6}, 18: {3, 5, 6}, 19: {3, 5, 6}, 20: {1, 3, 4, 5, 6}, 21: {1, 3, 4, 5, 6}, 22: {0, 2, 3, 4, 5}, 23: {0, 1, 2, 3, 4, 5}, 24: {0, 1, 2, 3}, 25: {0, 1, 2, 3, 4, 5, 6}, 26: {2, 3, 5, 6}, 27: {3, 5}, 28: {2, 3, 5, 6}, 29: {2, 3, 5}, 30: {2, 3, 5, 6}, 31: {0, 1, 2, 3, 4, 5, 6}, 32: {2, 3, 4}, 33: {2, 3, 4, 6}, 34: {2, 3, 4, 5}, 35: {3, 4, 6}, 36: {0, 1, 2, 3, 4, 5, 6}, 37: {0, 4}, 38: {0, 2, 3, 4, 5, 6}, 39: {1, 3, 4, 5, 6}, 40: {1, 2, 3, 4, 5, 6}, 41: {1, 3, 4, 5}, 42: {2, 3, 4}, 43: {3, 4}, 44: {1, 4, 5}}
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Best valset aggregate score so far: 0.6
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Best program as per aggregate score on valset: 3
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Best score on valset: 0.6
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Linear pareto front program index: 3
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 7: New program candidate index: 6
GEPA Optimization:  64%|██████▍   | 357/560 [33:37<18:39,  5.52s/rollouts]2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 8: No merge candidates found
2026/06/06 05:28:26 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Selected program 3 score: 0.6

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:14<00:00,  4.73s/it]

2026/06/06 05:28:40 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)

2026/06/06 05:29:23 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Proposed new text for predict: You are classifying a single natural-language air travel query into exactly one intent label.

Inputs you will receive:
- customer_message: a free-form query about air travel.
- intent_labels: a single line listing all possible labels for this task, delimited by %.

Your output:
- Return exactly one label string, exactly matching one of the labels provided in intent_labels (case and punctuation must match).
- Output only the label. Do not include explanations, reasoning, extra words, punctuation, or multiple labels.
- No surrounding quotes, and no leading/trailing spaces or extra newlines (just the single line with the label).

Core strategy:
1) Identify the information the user explicitly wants returned (the requested output), not the filters/constraints they include (cities, dates, times, airlines, or a specific fare amount often act as constraints).
2) Look for high-priority cues that determine specific labels (e.g., “how many”, “cheapest”, “what does X mean”).
3) If the user clearly asks for two aspects and a combined label exists (labels joined with “+”), choose that combined label.
4) If multiple aspects are asked but no appropriate combined label exists, choose the primary focus (the main thing the user asks to be listed/returned). Treat dates/times/cities/airlines/fare amounts as constraints unless the question is specifically about those as outputs.
5) Prefer specific question-type labels over generic topic labels when cues indicate them (e.g., quantity over flight).

Label meanings and common cues (include synonyms/phrases):
- flight: Requests for flights/schedules/availability without special emphasis on price or specific times. Cues: “show/list flights”, “what flights”, “schedules”, “availability”, “nonstop vs connecting”.
- flight_time: Specific departure/arrival times, durations, earliest/latest, or time-of-day as the asked output. Cues: “when”, “what time”, “arrival/departure time”, “arrive by/before/after”, “duration”, “earliest/latest flight”.
- airfare: Flight prices/fares. Cues: “price”, “cost”, “fare”, “how much” (about a flight ticket), “ticket price/rate”.
- aircraft: Aircraft type/equipment/plane model. Cues: “aircraft type”, “equipment”, “plane/jet type”, “Boeing/Airbus used”.
- ground_service: Ground transportation options to/from airports. Cues: “shuttle”, “taxi”, “bus”, “limousine”, “rental car”, “train to the airport”.
- airport: Airport info or which airports serve a city/area. Cues: “airport(s) in/near”, “which airport serves…”, “closest airport”.
- airline: Airline carriers serving a route/city. Cues: “which airlines”, “what carriers”, “who flies …”.
- distance: Distances between cities/airports. Cues: “distance”, “how far”, “miles/kilometers between”.
- abbreviation: Meaning/expansion of codes/abbreviations (airport/airline/fare codes). Cues: “what does X mean”, “what is X short for”, “code X meaning”.
- ground_fare: Prices/rates for ground transportation. Cues: “how much is the shuttle/taxi/limousine”, “bus fare”, “rental car rates/prices”.
- quantity: Counts or numbers of items. Cues: “how many”, “number of”, “count of” (applies to flights, airlines, cities, etc.).
- city: City listings/coverage by an airline. Cues: “what cities does [airline] serve”, “cities served”, “destinations”.
- flight_no: Flight number(s). Cues: “what is the flight number”, “flight no.”, “number of the flight”.
- capacity: Seat/aircraft capacity or seat availability. Cues: “capacity”, “how many seats”, “seats available/left”, “seat availability”.
- flight+airfare: Asking for flights and their prices together. Cues: “list/show flights with prices/fares”.
- meal: Meal service. Cues: “meals”, “meal served”, “food/snack/breakfast/lunch/dinner on the flight”.
- restriction: Fare rules/limitations. Cues: “restrictions”, “fare restrictions”, “ticket restrictions”, “air restrictions”, “refundable/nonrefundable”, “change fees”, “advance purchase”, “Saturday night stay”, “penalties”, “blackout dates”.
- airline+flight_no: Jointly asking for the airline(s) and the flight number(s). Cues: “airlines and flight numbers”.
- ground_service+ground_fare: Ground transport options plus their fares together. Cues: “shuttle and its price”, “taxi options and cost”.
- airfare+flight_time: Fare in relation to specific times, or jointly asking price and time. Cues: “fare for the 7 pm flight”, “price and time”, “cost of the evening/morning flight”.
- cheapest: Superlative/lowest price queries. Cues: “cheapest”, “lowest fare”, “least expensive”.
- aircraft+flight+flight_no: Combined request including aircraft type, flight(s), and flight number(s) together.

Priority and disambiguation rules:
- “How many …” → quantity (even if about flights/airlines/cities).
- “Cheapest/lowest/least expensive” → cheapest (do not use cheapest if a specific dollar amount is merely mentioned; that’s a constraint).
- “What does/code/meaning/stand for” → abbreviation (airport/airline/fare codes).
- “How much”:
  - If about a flight ticket → airfare.
  - If about ground transport → ground_fare.
- “Service/serve”:
  - If asking which cities an airline serves → city.
  - If asking which airlines serve a city/route → airline.
- Mentions of dates/times or time filters alone do not force flight_time unless the time itself is the requested output. Time constraints that filter other requested info do not change the label.
  - Example: “airlines and flight numbers … arriving before noon” → airline+flight_no (time is a filter).
- Combined labels take precedence when explicitly asking for exactly those combined aspects.
  - Examples: “airlines and flight numbers” → airline+flight_no; “flights with prices” → flight+airfare; “price and time” or “fare for the 7 pm flight” → airfare+flight_time.
- City/airline/airport names, dates, times, and even specific fare amounts (e.g., “for the airfare of $416”) generally act as filters unless the question is explicitly about those as outputs.

Tricky cases and reminders:
- “Air restrictions” or “fare/ticket restrictions” maps to restriction. A specific dollar fare mentioned (e.g., “for the airfare of 416 dollars”) is a constraint, not a request for price.
- “Rental car rates/prices” maps to ground_fare (ground transport pricing), not airfare.
- “Equipment” and “what type of plane/jet” map to aircraft.
- “Schedule(s)” maps to flight unless exact times are explicitly requested, in which case consider flight_time.
- Always choose from the provided intent_labels; do not invent labels or variants.

Execution checklist for each query:
1) Extract the exact information the user wants returned.
2) Check for high-priority cues (quantity, cheapest, abbreviation, how much).
3) If two aspects are clearly requested and a matching combined label exists, use it.
4) Otherwise choose the most specific single label matching the requested information; treat time/date/city/airline/fare-amount mentions as filters.
5) Output only the exact matching label from intent_labels, on a single line.
2026/06/06 05:29:38 INFO dspy.evaluate.evaluate: Average Metric: 3 / 3 (100.0%)
2026/06/06 05:29:38 INFO dspy.teleprompt.gepa.gepa: Iteration 8: New subsample score 3 is better than old score 2. Continue to full eval and add to candidate pool.
2026/06/06 05:31:58 INFO dspy.evaluate.evaluate: Average Metric: 26 / 45 (57.8%)
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Valset score for new program: 0.5777777777777777 (coverage 45 / 45)
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Val aggregate for new program: 0.5777777777777777
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Individual valset scores for new program: {0: False, 1: True, 2: True, 3: False, 4: True, 5: False, 6: False, 7: True, 8: False, 9: False, 10: False, 11: True, 12: False, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: False, 25: False, 26: True, 27: False, 28: True, 29: True, 30: True, 31: True, 32: False, 33: True, 34: True, 35: False, 36: False, 37: False, 38: False, 39: False, 40: True, 41: True, 42: False, 43: False, 44: True}
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: New valset pareto front scores: {0: True, 1: True, 2: True, 3: False, 4: True, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Valset pareto front aggregate score: 0.9333333333333333
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Updated valset pareto front programs: {0: {1, 5, 6}, 1: {0, 1, 6, 7}, 2: {6, 7}, 3: {0, 1, 2, 3, 4, 5, 6, 7}, 4: {6, 7}, 5: {1, 6}, 6: {1}, 7: {0, 1, 2, 4, 5, 6, 7}, 8: {1}, 9: {0, 1, 2, 3, 4, 5, 6, 7}, 10: {1, 6}, 11: {0, 1, 2, 3, 4, 5, 7}, 12: {0, 1, 2, 5}, 13: {1, 2, 7}, 14: {0, 1, 2, 3, 4, 5, 6, 7}, 15: {2, 6, 7}, 16: {1, 2, 4, 5, 7}, 17: {0, 1, 3, 4, 5, 6, 7}, 18: {3, 5, 6, 7}, 19: {3, 5, 6, 7}, 20: {1, 3, 4, 5, 6, 7}, 21: {1, 3, 4, 5, 6, 7}, 22: {0, 2, 3, 4, 5, 7}, 23: {0, 1, 2, 3, 4, 5, 7}, 24: {0, 1, 2, 3}, 25: {0, 1, 2, 3, 4, 5, 6, 7}, 26: {2, 3, 5, 6, 7}, 27: {3, 5}, 28: {2, 3, 5, 6, 7}, 29: {2, 3, 5, 7}, 30: {2, 3, 5, 6, 7}, 31: {0, 1, 2, 3, 4, 5, 6, 7}, 32: {2, 3, 4}, 33: {2, 3, 4, 6, 7}, 34: {2, 3, 4, 5, 7}, 35: {3, 4, 6}, 36: {0, 1, 2, 3, 4, 5, 6}, 37: {0, 4}, 38: {0, 2, 3, 4, 5, 6}, 39: {1, 3, 4, 5, 6}, 40: {1, 2, 3, 4, 5, 6, 7}, 41: {1, 3, 4, 5, 7}, 42: {2, 3, 4}, 43: {3, 4}, 44: {1, 4, 5, 7}}
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Best valset aggregate score so far: 0.6
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Best program as per aggregate score on valset: 3
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Best score on valset: 0.6
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Linear pareto front program index: 3
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: New program candidate index: 7
GEPA Optimization:  73%|███████▎  | 408/560 [37:09<12:49,  5.06s/rollouts]2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 9: No merge candidates found
2026/06/06 05:31:58 INFO dspy.teleprompt.gepa.gepa: Iteration 9: Selected program 7 score: 0.5777777777777777

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:13<00:00,  4.41s/it]

2026/06/06 05:32:12 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)

2026/06/06 05:33:32 INFO dspy.teleprompt.gepa.gepa: Iteration 9: Proposed new text for predict: Task: Classify a single natural-language air travel query into exactly one intent label.

Inputs you will receive:
- customer_message: a free-form query about air travel.
- intent_labels: a single line listing all possible labels for this task, delimited by %.

Your output:
- Return exactly one label string, exactly matching one of the labels provided in intent_labels (case and punctuation must match).
- Output only the label. Do not include explanations, reasoning, extra words, punctuation, or multiple labels.
- No surrounding quotes, and no leading/trailing spaces or extra newlines (just the single line with the label).

Core strategy:
1) Identify the single piece of information the user explicitly wants returned (the requested output), not the filters/constraints they include. Cities, dates, times, airlines, and even a specific fare amount usually act as filters unless the question is explicitly about those as outputs.
2) Look for high-priority cues that directly map to specific labels (e.g., “how many” → quantity; “cheapest” → cheapest; “what does X mean” → abbreviation).
3) If the user clearly asks for two aspects and a matching combined label exists (joined with “+”), choose that combined label.
4) If multiple aspects are asked and no matching combined label exists, choose the primary focus (the main item the user asks to be listed/returned). Treat dates/times/cities/airlines/fare-amount mentions as filters.
5) Prefer specific question-type labels over generic topic labels when cues indicate them (e.g., quantity over flight).

Label meanings and reliable cues:
- flight: Lists/requests for flights, schedules, or availability without specific emphasis on exact times or prices. Cues: “show/list flights”, “what flights”, “schedules”, “availability”, “nonstop vs connecting”.
- flight_time: Specific departure/arrival times, durations, earliest/latest flights, or time-of-day when the time itself about a flight is the requested output. Cues: “when”, “what time”, “arrival/departure time”, “arrive by/before/after”, “duration”, “earliest/latest flight”.
- airfare: Flight prices/fares. Cues: “price”, “cost”, “fare”, “how much” (about a flight ticket), “ticket price/rate”.
- aircraft: Aircraft type/equipment/plane model. Cues: “aircraft type”, “equipment”, “plane/jet type”, “Boeing/Airbus used”.
- ground_service: Ground transportation options or info to/from airports (including travel time/duration for ground transport). Cues: “shuttle”, “taxi”, “bus”, “limousine”, “rental car”, “train”, “metro”, “how long from airport to downtown/city”.
- airport: Airport info or which airports serve a city/area, including proximity/closest-to-downtown questions. Cues: “airport(s) in/near”, “which airport serves…”, “closest airport to downtown”.
- airline: Airline carriers serving a route/city. Cues: “which airlines”, “what carriers”, “who flies …”.
- distance: Distances between cities/airports. Cues: “distance”, “how far”, “miles/kilometers between”.
- abbreviation: Meaning/expansion of codes/abbreviations (airport/airline/fare codes). Cues: “what does X mean”, “what is X short for”, “code X meaning”.
- ground_fare: Prices/rates for ground transportation. Cues: “how much is the shuttle/taxi/limousine”, “bus fare”, “rental car rates/prices”.
- quantity: Counts or numbers of items. Cues: “how many”, “number of”, “count of” (applies to flights, airlines, airports, cities, etc.).
- city: City listings/coverage by an airline. Cues: “what cities does [airline] serve”, “cities served”, “destinations”.
- flight_no: Flight number(s). Cues: “what is the flight number”, “flight no.”, “number of the flight”.
- capacity: Seat/aircraft capacity or seat availability. Cues: “capacity”, “how many seats”, “seats available/left”, “seat availability”.
- flight+airfare: Joint request for flights and their prices. Cues: “list/show flights with prices/fares”.
- meal: Meal service. Cues: “meals”, “meal served”, “food/snack/breakfast/lunch/dinner on the flight”.
- restriction: Fare/ticket rules and limitations. Cues: “restrictions”, “fare restrictions”, “ticket restrictions”, “air restrictions”, “refundable/nonrefundable”, “change fees”, “advance purchase”, “Saturday night stay”, “penalties”, “blackout dates”.
- airline+flight_no: Joint request for the airline(s) and the flight number(s). Cues: explicitly asking for both airlines and flight numbers together.
- ground_service+ground_fare: Ground transport options plus their fares together. Cues: “shuttle/taxi options and cost”, “ground transportation and price”.
- airfare+flight_time: Fare in relation to specific times, or joint request for price and time. Cues: “fare for the 7 pm flight”, “price and time”, “cost of the evening/morning flight”.
- cheapest: Superlative/lowest price queries. Cues: “cheapest”, “lowest fare”, “least expensive”.
- aircraft+flight+flight_no: Combined request including aircraft type, flight(s), and flight number(s) together.

High-priority disambiguation rules:
- “How many …” → quantity (even if about flights/airlines/airports/cities).
- “Cheapest/lowest/least expensive” → cheapest (do not use cheapest if a specific dollar amount is merely mentioned; that’s a constraint).
- “What does/code/meaning/stand for” → abbreviation (airport/airline/fare codes).
- “How much”:
  - If about a flight ticket → airfare.
  - If about ground transport → ground_fare.
- Time/duration questions:
  - If the question is about flights (departure/arrival times, duration of a flight) → flight_time.
  - If the question is about ground transportation to/from an airport (e.g., “how long from [airport] to downtown”) → ground_service.
  - If the question is about distance in miles/km (not time) → distance.
- Mentions of dates/times or time filters do not force flight_time unless time itself is the requested output. Time constraints that filter other requested info do not change the label.
  - Example: “airlines and flight numbers … arriving before noon” → airline+flight_no (time is a filter).
- Combined labels take precedence when explicitly and exactly asking for those combined aspects.
  - Examples: “airlines and flight numbers” → airline+flight_no; “flights with prices” → flight+airfare; “price and time” or “fare for the 7 pm flight” → airfare+flight_time.
- City/airline/airport names, dates, times, and specific fare amounts (e.g., “for the airfare of $416”) generally act as filters unless the question is explicitly about those as outputs.

Tricky cases and reminders:
- “Air restrictions” or “fare/ticket restrictions” → restriction.
- “Rental car rates/prices” → ground_fare (ground transport pricing), not airfare.
- “Equipment” and “what type of plane/jet” → aircraft.
- “Schedule(s)” usually → flight unless exact times are explicitly requested, in which case consider flight_time.
- “Closest/nearest airport to downtown” → airport (airport info/proximity).
- Ground transportation topics (options, how to get to/from the airport, and even travel time for those options) → ground_service.
- Always choose from the provided intent_labels; do not invent labels or variants.

Execution checklist for each query:
1) Extract the exact information the user wants returned.
2) Check for high-priority cues (quantity, cheapest, abbreviation, how much).
3) If two aspects are clearly requested and a matching combined label exists, use it.
4) Otherwise choose the most specific single label matching the requested information; treat time/date/city/airline/fare-amount mentions as filters unless explicitly requested as outputs.
5) Output only the exact matching label from intent_labels, on a single line.

Sanity-check with examples:
- “what airport in new york is closest to downtown” → airport.
- “how long is a trip from philadelphia airport to downtown philadelphia” → ground_service (ground transport travel time).
- “tell me about ground transportation at salt lake city” → ground_service.
2026/06/06 05:33:49 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:33:49 INFO dspy.teleprompt.gepa.gepa: Iteration 9: New subsample score 2 is not better than old score 2, skipping
GEPA Optimization:  74%|███████▍  | 414/560 [39:00<14:03,  5.78s/rollouts]2026/06/06 05:33:49 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Selected program 1 score: 0.5111111111111111

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:13<00:00,  4.58s/it]

2026/06/06 05:34:03 INFO dspy.evaluate.evaluate: Average Metric: 0 / 3 (0.0%)

2026/06/06 05:34:58 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Proposed new text for predict: You are a single-label intent classifier for ATIS-style travel/transport queries.

Inputs:
- customer_message: a natural-language query about travel/transport.
- intent_labels: a single string of valid labels separated by %.

Your output:
- Return exactly one label, chosen verbatim from intent_labels.
- Output only the label (no extra text, punctuation, or explanations).

Core selection strategy:
1) Prefer the most specific label available. If the user clearly requests two aspects and a corresponding combined label exists, choose the combined label. Otherwise choose the single most specific label.

2) Domain mappings and synonyms (air travel and ground transport):
- flight: list/find flights or availability/schedules (e.g., “show me flights from X to Y [on DAY/time]”, “find flights”). Route/day/time constraints alone still map to flight unless another aspect (price, duration, etc.) is explicitly requested.
- airfare: flight price/cost/fare (e.g., “how much is the ticket/fare/price”, “what does it cost”).
- flight_time: duration/time en route (e.g., “how long does it take”, “flight time”, “duration”).
- aircraft: aircraft/equipment type (e.g., “what kind of plane/equipment”).
- airport: airport names/codes/info (e.g., “DFW airport”, “which airport”).
- airline: carrier information (e.g., “which airline”, “what airline flies …”).
- distance: distance between cities/airports (e.g., “how far”, “miles”, “distance”).
- ground_service: non-price ground transport options to/from airports (e.g., “is there a shuttle/taxi/limousine/bus”, “what ground transportation is available”).
- ground_fare: price/cost of ground transport (e.g., “how much is a taxi/limousine/shuttle”, “ground fare”).
- cheapest: explicitly seeking the lowest-price flight (e.g., “cheapest/lowest fare/lowest price flight”).
- quantity: counts (e.g., “how many flights/stops”).
- city: city identification/which cities are served.
- flight_no: requests for a specific flight number or about a specific numbered flight (e.g., “what is the flight number”, “tell me the flight number”, “what does flight 123 do”).
- capacity: seat capacity/number of seats.
- meal: meal availability on flights.
- restriction: fare/ticket restrictions (e.g., “Saturday night stay, change penalties, advance purchase”).
- abbreviation: expansions/meanings of abbreviations/codes (e.g., “what does DFW stand for”).

Combined labels (use when both aspects are clearly requested):
- flight+airfare: requesting flights and their fares/prices together (e.g., “show me all flights and fares …”, “list flights with prices …”).
- airfare+flight_time: requesting both price and duration/time (e.g., “how much and how long …”).
- ground_service+ground_fare: requesting ground options and their prices (e.g., “what shuttles are available and how much …”).
- airline+flight_no: linking airline and flight number in either direction:
  - “which airline operates flight 123”
  - “what is the flight number for the Delta/Continental flight …”
  - “airline and flight number from X to Y”
- aircraft+flight+flight_no: aircraft type tied to a specific flight/number (e.g., “what aircraft is used on flight 123”, or aircraft info tied to a particular listed flight).

Disambiguation rules:
- “how long does it take” → flight_time (do not choose distance unless “how far”, “miles”, or “distance” is explicitly asked).
- Mentions of price/cost/fare/“how much”:
  - Flights → airfare.
  - Ground transport (taxi/limousine/shuttle/bus) → ground_fare.
- Mentions of ground transport without price → ground_service.
- If both aspects are clearly requested and a combined label exists (e.g., airfare+flight_time, ground_service+ground_fare, flight+airfare, airline+flight_no), choose the combined label.
- Day/time constraints (e.g., “Wednesday”, “at 12:20 pm”, “in the morning”) do not change the intent; they still map to flight unless price/time/etc. is explicitly asked.

Critical pitfalls to avoid (learned from prior errors):
- If the query asks for both “airline” and “flight number” (or asks for a flight number while specifying an airline), choose airline+flight_no, not flight or flight_no.
  - Examples:
    - “airline and flight number from Columbus to Minneapolis” → airline+flight_no
    - “what is the flight number for the Continental flight which leaves Denver at 12:20 pm and goes to San Francisco” → airline+flight_no
- If the query requests “flights and fares” together, choose flight+airfare, not flight.
  - Example: “show me all flights and fares from Denver to San Francisco” → flight+airfare

Formatting:
- Return only one label string, exactly as it appears in intent_labels (case and punctuation must match).
- Do not invent labels; select only from those provided in intent_labels.
2026/06/06 05:35:14 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:35:14 INFO dspy.teleprompt.gepa.gepa: Iteration 10: New subsample score 2 is better than old score 0. Continue to full eval and add to candidate pool.
2026/06/06 05:37:46 INFO dspy.evaluate.evaluate: Average Metric: 16 / 45 (35.6%)
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Valset score for new program: 0.35555555555555557 (coverage 45 / 45)
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Val aggregate for new program: 0.35555555555555557
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Individual valset scores for new program: {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: False, 9: False, 10: True, 11: True, 12: False, 13: True, 14: True, 15: True, 16: False, 17: True, 18: False, 19: False, 20: False, 21: True, 22: True, 23: True, 24: False, 25: False, 26: False, 27: False, 28: False, 29: False, 30: False, 31: True, 32: False, 33: False, 34: False, 35: False, 36: False, 37: False, 38: False, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: New valset pareto front scores: {0: True, 1: True, 2: True, 3: False, 4: True, 5: True, 6: True, 7: True, 8: True, 9: False, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Valset pareto front aggregate score: 0.9333333333333333
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Updated valset pareto front programs: {0: {1, 5, 6}, 1: {0, 1, 6, 7}, 2: {6, 7}, 3: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 4: {6, 7}, 5: {1, 6}, 6: {1}, 7: {0, 1, 2, 4, 5, 6, 7}, 8: {1}, 9: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 10: {8, 1, 6}, 11: {0, 1, 2, 3, 4, 5, 7, 8}, 12: {0, 1, 2, 5}, 13: {8, 1, 2, 7}, 14: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 15: {8, 2, 6, 7}, 16: {1, 2, 4, 5, 7}, 17: {0, 1, 3, 4, 5, 6, 7, 8}, 18: {3, 5, 6, 7}, 19: {3, 5, 6, 7}, 20: {1, 3, 4, 5, 6, 7}, 21: {1, 3, 4, 5, 6, 7, 8}, 22: {0, 2, 3, 4, 5, 7, 8}, 23: {0, 1, 2, 3, 4, 5, 7, 8}, 24: {0, 1, 2, 3}, 25: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 26: {2, 3, 5, 6, 7}, 27: {3, 5}, 28: {2, 3, 5, 6, 7}, 29: {2, 3, 5, 7}, 30: {2, 3, 5, 6, 7}, 31: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 32: {2, 3, 4}, 33: {2, 3, 4, 6, 7}, 34: {2, 3, 4, 5, 7}, 35: {3, 4, 6}, 36: {0, 1, 2, 3, 4, 5, 6}, 37: {0, 4}, 38: {0, 2, 3, 4, 5, 6}, 39: {1, 3, 4, 5, 6, 8}, 40: {1, 2, 3, 4, 5, 6, 7, 8}, 41: {1, 3, 4, 5, 7, 8}, 42: {8, 2, 3, 4}, 43: {8, 3, 4}, 44: {1, 4, 5, 7, 8}}
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Best valset aggregate score so far: 0.6
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Best program as per aggregate score on valset: 3
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Best score on valset: 0.6
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Linear pareto front program index: 3
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 10: New program candidate index: 8
GEPA Optimization:  83%|████████▎ | 465/560 [42:57<08:26,  5.34s/rollouts]2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 11: No merge candidates found
2026/06/06 05:37:46 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Selected program 7 score: 0.5777777777777777

Average Metric: 3.00 / 3 (100.0%): 100%|██████████| 3/3 [00:15<00:00,  5.32s/it]

2026/06/06 05:38:02 INFO dspy.evaluate.evaluate: Average Metric: 3 / 3 (100.0%)
2026/06/06 05:38:02 INFO dspy.teleprompt.gepa.gepa: Iteration 11: All subsample scores perfect. Skipping.
2026/06/06 05:38:02 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Reflective mutation did not propose a new candidate
GEPA Optimization:  84%|████████▎ | 468/560 [43:13<08:10,  5.34s/rollouts]2026/06/06 05:38:02 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Selected program 3 score: 0.6

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:18<00:00,  6.23s/it]

2026/06/06 05:38:21 INFO dspy.evaluate.evaluate: Average Metric: 1 / 3 (33.3%)

2026/06/06 05:39:10 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Proposed new text for predict: Task: Classify a single natural-language air travel query into exactly one intent label.

Inputs you will receive:
- customer_message: a free-form user query about air travel.
- intent_labels: a single line containing all valid labels for this task, delimited by %.

Your output:
- Return exactly one label string that exactly matches one of the labels in intent_labels (case and punctuation must match).
- Output only the label on a single line. Do not include explanations, reasoning, extra words, punctuation, or additional whitespace.

Core decision strategy:
1) Identify the specific information the user wants returned (the requested output), not the filters/constraints (cities, dates, times, airlines usually act as constraints).
2) Apply high-priority cue rules (e.g., “how many” → quantity, “cheapest” → cheapest, “what does/what is [code]” → abbreviation).
3) If the query clearly requests two aspects and an exact combined label exists (labels joined with “+”), choose that combined label.
4) If multiple aspects are mentioned but no exact combined label exists, choose the primary focus (the main item the user wants listed/returned).
5) Prefer the most specific/question-type label over a generic topic label when cues indicate it.

Label meanings and cues:
- flight: Requests for flights/schedules/availability without special emphasis on exact times or prices. Cues: “show/list flights”, “schedule(s)” (time-neutral), “what flights are available”, “nonstop vs connecting”.
- flight_time: Exact times, durations, or time-of-day are the requested output. Cues: “what time”, “when”, “arrival/departure time”, “arrive by/before/after”, “duration”, “earliest/latest”, “morning/afternoon/evening flight times”, “schedule of morning/evening flights”.
  - Important: “Schedule” alone maps to flight, but “schedule” combined with explicit time-of-day focus (e.g., “schedule of morning flights”) maps to flight_time.
- airfare: Flight prices/fare amounts. Cues: “price”, “cost”, “fare”, “how much” (about flight ticket price).
- aircraft: Aircraft type/equipment/plane model. Cues: “aircraft type”, “equipment”, “plane/jet model”, “Boeing/Airbus used”.
- ground_service: Ground transportation to/from airports. Cues: “shuttle”, “taxi”, “bus”, “limousine”, “rental car”, “train to the airport”.
- airport: Airport info or which airports serve a city/area. Cues: “airport(s) in/near”, “which airport serves”, “closest airport”.
- airline: Airlines serving a city/route. Cues: “which airlines”, “what carriers”, “who flies …”.
- distance: Distances between cities/airports. Cues: “distance”, “how far”, “miles/kilometers between”.
- abbreviation: Meaning/expansion of codes (airport/airline/fare/equipment codes). Cues: “what does X mean”, “what is X short for”, “code X meaning”, “what is MCO/JFK/AA/Y fare”.
  - Domain cue: A lone 2–3 letter all-caps token like MCO, JFK, AA typically indicates a code; “what is/what’s [CODE]” → abbreviation (do not choose airport).
- ground_fare: Prices for ground transportation. Cues: “how much is the shuttle/taxi/limousine”, “bus fare”, “ground fare”.
- quantity: Counts or numbers of items. Cues: “how many”, “number of”, “count of” (applies regardless of subject: flights, airlines, cities, seats).
- city: City listings/coverage by an airline. Cues: “what cities does [airline] serve”, “cities served/destinations”.
- flight_no: Flight number(s). Cues: “what is the flight number”, “flight no.”.
- capacity: Seat/aircraft capacity or seat availability. Cues: “capacity”, “how many seats”, “seats available/left”.
  - Domain cue: Numeric equipment codes like “733” (Boeing 737-300) can appear; “capacity of 733” → capacity (do not treat as a flight number).
- flight+airfare: Jointly asking for flights and their prices. Cues: “flights with prices/fares”, “list flights and fares”.
- meal: Meal service. Cues: “meals”, “meal served”, “food/snack/breakfast/lunch/dinner on the flight”.
- restriction: Fare rules/limitations. Cues: “restrictions”, “refundable/nonrefundable”, “change fees”, “advance purchase”, “Saturday night stay”, “penalties”, “blackout dates”.
- airline+flight_no: Jointly asking for airline(s) and flight number(s). Cues: “airlines and flight numbers”.
- ground_service+ground_fare: Ground transport plus its fare together. Cues: “shuttle options and price”, “taxi options and cost”.
- airfare+flight_time: Price in relation to specific times, or jointly asking price and time. Cues: “price and time”, “fare for the 7 pm flight”, “cost of the morning/evening flight”.
- cheapest: Superlatives for lowest price. Cues: “cheapest”, “lowest fare”, “least expensive”.

Priority and disambiguation rules:
- “How many …” → quantity (overrides other subjects).
- “Cheapest/lowest/least expensive” → cheapest (overrides airfare).
- “What does/what is [code]/meaning/stand for” → abbreviation (for airport/airline/fare/equipment codes like MCO, JFK, AA, Y, 733).
- “How much”:
  - If clearly about a flight ticket → airfare.
  - If clearly about ground transport → ground_fare.
- “Service/serve”:
  - If asking which cities an airline serves → city.
  - If asking which airlines serve a city/route → airline.
- Times/dates/cities/airlines typically act as filters unless the question is specifically about those as outputs.
  - Time as filter example: “airlines and flight numbers arriving before noon” → airline+flight_no.
  - Time as output examples: “when does it depart”, “what are the morning flight times”, “schedule of morning flights” → flight_time.
- Combined labels take precedence when the query explicitly requests exactly those combined aspects.
  - “airlines and flight numbers” → airline+flight_no.
  - “flights with prices” → flight+airfare.
  - “price and time” or “fare for the 7 pm flight” → airfare+flight_time.

Execution checklist:
1) Extract the exact information the user wants returned (the output), ignoring filters like cities, dates, times, and airlines unless they are the requested output.
2) Check for high-priority cues (quantity, cheapest, abbreviation, how much).
3) If two aspects are clearly requested and a matching combined label exists, pick that combined label.
4) Otherwise, choose the most specific single label matching the requested output.
5) Return only the exact label from intent_labels on a single line with no extra text or whitespace.

Remember key edge cases:
- “What is MCO/JFK/AA/Y/733?” → abbreviation.
- “Schedule of morning flights” or explicit time-of-day emphasis → flight_time.
- “Capacity of a 733” → capacity.
- “Schedule” without explicit time focus → flight.
2026/06/06 05:39:28 INFO dspy.evaluate.evaluate: Average Metric: 2 / 3 (66.7%)
2026/06/06 05:39:28 INFO dspy.teleprompt.gepa.gepa: Iteration 12: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
2026/06/06 05:42:16 INFO dspy.evaluate.evaluate: Average Metric: 34 / 45 (75.6%)
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Found a better program on the valset with score 0.7555555555555555.
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Valset score for new program: 0.7555555555555555 (coverage 45 / 45)
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Val aggregate for new program: 0.7555555555555555
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Individual valset scores for new program: {0: True, 1: True, 2: False, 3: False, 4: False, 5: False, 6: True, 7: True, 8: True, 9: True, 10: True, 11: True, 12: True, 13: False, 14: True, 15: True, 16: True, 17: True, 18: False, 19: False, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: False, 37: False, 38: True, 39: True, 40: True, 41: True, 42: False, 43: True, 44: True}
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: New valset pareto front scores: {0: True, 1: True, 2: True, 3: False, 4: True, 5: True, 6: True, 7: True, 8: True, 9: True, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Valset pareto front aggregate score: 0.9555555555555556
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Updated valset pareto front programs: {0: {1, 5, 6, 9}, 1: {0, 1, 6, 7, 9}, 2: {6, 7}, 3: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 4: {6, 7}, 5: {1, 6}, 6: {1, 9}, 7: {0, 1, 2, 4, 5, 6, 7, 9}, 8: {1, 9}, 9: {9}, 10: {8, 1, 6, 9}, 11: {0, 1, 2, 3, 4, 5, 7, 8, 9}, 12: {0, 1, 2, 5, 9}, 13: {8, 1, 2, 7}, 14: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 15: {2, 6, 7, 8, 9}, 16: {1, 2, 4, 5, 7, 9}, 17: {0, 1, 3, 4, 5, 6, 7, 8, 9}, 18: {3, 5, 6, 7}, 19: {3, 5, 6, 7}, 20: {1, 3, 4, 5, 6, 7, 9}, 21: {1, 3, 4, 5, 6, 7, 8, 9}, 22: {0, 2, 3, 4, 5, 7, 8, 9}, 23: {0, 1, 2, 3, 4, 5, 7, 8, 9}, 24: {0, 1, 2, 3, 9}, 25: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 26: {2, 3, 5, 6, 7, 9}, 27: {9, 3, 5}, 28: {2, 3, 5, 6, 7, 9}, 29: {2, 3, 5, 7, 9}, 30: {2, 3, 5, 6, 7, 9}, 31: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 32: {9, 2, 3, 4}, 33: {2, 3, 4, 6, 7, 9}, 34: {2, 3, 4, 5, 7, 9}, 35: {9, 3, 4, 6}, 36: {0, 1, 2, 3, 4, 5, 6}, 37: {0, 4}, 38: {0, 2, 3, 4, 5, 6, 9}, 39: {1, 3, 4, 5, 6, 8, 9}, 40: {1, 2, 3, 4, 5, 6, 7, 8, 9}, 41: {1, 3, 4, 5, 7, 8, 9}, 42: {8, 2, 3, 4}, 43: {8, 9, 3, 4}, 44: {1, 4, 5, 7, 8, 9}}
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Best valset aggregate score so far: 0.7555555555555555
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Best program as per aggregate score on valset: 9
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Best score on valset: 0.7555555555555555
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Linear pareto front program index: 9
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 12: New program candidate index: 9
GEPA Optimization:  93%|█████████▎| 519/560 [47:27<03:32,  5.18s/rollouts]2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 13: No merge candidates found
2026/06/06 05:42:16 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Selected program 9 score: 0.7555555555555555

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:14<00:00,  4.78s/it]

2026/06/06 05:42:31 INFO dspy.evaluate.evaluate: Average Metric: 1 / 3 (33.3%)

2026/06/06 05:43:16 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Proposed new text for predict: Task: Classify a single natural-language air travel query into exactly one intent label.

Inputs you will receive:
- customer_message: a free-form user query about air travel.
- intent_labels: a single line containing all valid labels for this task, delimited by %.

Your output:
- Return exactly one label string that exactly matches one of the labels in intent_labels (case and punctuation must match).
- Output only the label on a single line. Do not include explanations, reasoning, extra words, punctuation, or additional whitespace.

Core decision strategy:
1) Identify the specific information the user wants returned (the requested output), not the filters/constraints (cities, dates, times, airlines usually act as constraints).
2) Apply high-priority cue rules (e.g., “how many” → quantity, “cheapest” → cheapest, “what does/what is [code]” → abbreviation).
3) If the query clearly requests two aspects and an exact combined label exists (labels joined with “+”), choose that combined label.
4) If multiple aspects are mentioned but no exact combined label exists, choose the primary focus (the main item the user wants listed/returned).
5) Prefer the most specific/question-type label over a generic topic label when cues indicate it.

Label meanings and key cues:
- flight: Requests for flights/schedules/availability without special emphasis on exact times or prices.
  - Cues: “show/list flights”, “schedule(s)” (time-neutral), “what flights are available”, “nonstop vs connecting”.
  - Important: Dates like “Wednesday/June 10” are filters and keep this as flight (do NOT switch to flight_time just because a day/date is present).
- flight_time: Exact times, durations, or time-of-day are the requested output.
  - Cues: “what time”, “when”, “arrival/departure time”, “arrive by/before/after”, “duration”, “earliest/latest”, “morning/afternoon/evening flight times”, “schedule of morning/evening flights”.
  - “Schedule” alone → flight; “schedule” with explicit time-of-day focus → flight_time.
- airfare: Flight prices/fare amounts.
  - Cues: “price”, “cost”, “fare”, “how much” (when clearly about a flight ticket).
- aircraft: Aircraft type/equipment/plane model.
  - Cues: “aircraft type”, “equipment”, “plane/jet model”, “Boeing/Airbus used”.
- ground_service: Ground transportation to/from airports.
  - Cues: “shuttle”, “taxi”, “bus”, “limousine”, “rental car”, “train to the airport”.
- airport: Airport info or which airports serve a city/area.
  - Cues: “airport(s) in/near”, “which airport serves”, “closest airport”.
- airline: Airlines serving a city/route.
  - Cues: “which airlines”, “what carriers”, “who flies …”.
- distance: Distances between cities/airports.
  - Cues: “distance”, “how far”, “miles/kilometers between”.
- abbreviation: Meaning/expansion of codes (airport/airline/fare/equipment codes).
  - Cues: “what does X mean”, “what is X short for”, “code X meaning”, “what is MCO/JFK/AA/Y”.
  - Domain cue: A lone 2–3 letter all-caps token like MCO, JFK, AA typically indicates a code; “what is/does [CODE]” → abbreviation (do not choose airport/airline).
- ground_fare: Prices for ground transportation.
  - Cues: “how much is the shuttle/taxi/limousine”, “bus fare”, “ground fare”.
- quantity: Counts or numbers of items (overrides subject).
  - Cues: “how many”, “number of”, “count of” (applies to flights, airlines, cities, seats, etc.).
- city: City listings/coverage by an airline.
  - Cues: “what cities does [airline] serve”, “cities served/destinations”.
- flight_no: Flight number(s).
  - Cues: “what is the flight number”, “flight no.”.
- capacity: Seat/aircraft capacity or seat availability.
  - Cues: “capacity”, “how many seats”, “seats available/left”.
  - Domain cue: Numeric equipment codes like “733” can appear; “capacity of 733” → capacity (do not treat as a flight number).
- meal: Meal service.
  - Cues: “meals”, “meal served”, “food/snack/breakfast/lunch/dinner on the flight”.
- restriction: Fare rules/limitations.
  - Cues: “restrictions”, “refundable/nonrefundable”, “change fees”, “advance purchase”, “Saturday night stay”, “penalties”, “blackout dates”.

Combined labels (choose only when the query explicitly asks for exactly those aspects together):
- flight+airfare: Jointly asking for flights and their prices.
  - Cues: “flights with prices/fares”, “list flights and fares”.
- airfare+flight_time: Price in relation to specific times, or jointly asking price and time.
  - Cues: “price and time”, “fare for the 7 pm flight”, “cost of the morning/evening flight”.
- airline+flight_no: Jointly asking for airline(s) and flight number(s).
  - Cues: “airlines and flight numbers”.
- ground_service+ground_fare: Ground transport options plus their fares together.
  - Cues: “shuttle/taxi options and price/cost”.
- Other combined labels may appear in intent_labels; select them only if the query explicitly requests exactly those components.

Priority and disambiguation rules:
- “How many …” → quantity (overrides other subjects).
- “Cheapest/lowest/least expensive” → cheapest (overrides airfare).
- “What does/what is [code]/meaning/stand for” → abbreviation (for codes like MCO, JFK, AA, Y, 733).
- “How much”:
  - If clearly about a flight ticket → airfare.
  - If clearly about ground transport → ground_fare.
- “Service/serve”:
  - If asking which cities an airline serves → city.
  - If asking which airlines serve a city/route → airline.
- Times/dates/cities/airlines typically act as filters unless the question is specifically about those as outputs.
  - Time as filter examples: “arriving before noon”, “leaves at 12:20 pm”, “on Wednesday” → keep the main label (do NOT switch to flight_time unless time is the requested output).
  - Time as output examples: “when does it depart”, “what are the morning flight times”, “schedule of morning flights” → flight_time.
- Combined labels take precedence when the query explicitly requests exactly those combined aspects.
  - “airlines and flight numbers” → airline+flight_no.
  - “flights with prices” → flight+airfare.
  - “price and time” or “fare for the 7 pm flight” → airfare+flight_time.
- If multiple aspects are mentioned but no exact combined label exists, choose the primary focus (what the user wants listed/returned).

Execution checklist:
1) Extract the exact information the user wants returned (the output), ignoring filters like cities, dates, times, and airlines unless they are the requested output.
2) Check for high-priority cues (quantity, cheapest, abbreviation, how much).
3) If two aspects are clearly requested and a matching combined label exists, pick that combined label.
4) Otherwise, choose the most specific single label matching the requested output.
5) Return only the exact label from intent_labels on a single line with no extra text or whitespace.

Common pitfalls and corrections:
- “show me flights from denver to washington dc wednesday” → flight (date is a filter; do not choose flight_time).
- “what is the flight number for the continental flight which leaves denver at 1220 pm and goes to san francisco” → flight_no (time is a filter).
- “airlines and flight numbers … arriving before noon” → airline+flight_no (arrival time is a filter; do not choose flight_time or flight+airfare).
- “schedule of morning flights” → flight_time (explicit time-of-day emphasis).
- “what is MCO/JFK/AA/Y/733?” → abbreviation.
- “capacity of a 733” → capacity.

Strict output format:
- Output must be exactly one of the labels present in intent_labels.
- Case and punctuation must match exactly.
- Output only the label on a single line; no explanations, no extra spaces, no punctuation.
2026/06/06 05:43:34 INFO dspy.evaluate.evaluate: Average Metric: 3 / 3 (100.0%)
2026/06/06 05:43:34 INFO dspy.teleprompt.gepa.gepa: Iteration 13: New subsample score 3 is better than old score 1. Continue to full eval and add to candidate pool.
2026/06/06 05:46:05 INFO dspy.evaluate.evaluate: Average Metric: 33 / 45 (73.3%)
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Valset score for new program: 0.7333333333333333 (coverage 45 / 45)
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Val aggregate for new program: 0.7333333333333333
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Individual valset scores for new program: {0: False, 1: True, 2: True, 3: False, 4: False, 5: True, 6: True, 7: True, 8: False, 9: True, 10: True, 11: True, 12: True, 13: False, 14: True, 15: True, 16: False, 17: True, 18: True, 19: True, 20: False, 21: True, 22: False, 23: True, 24: True, 25: False, 26: True, 27: False, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: False, 38: True, 39: True, 40: True, 41: True, 42: False, 43: True, 44: True}
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: New valset pareto front scores: {0: True, 1: True, 2: True, 3: False, 4: True, 5: True, 6: True, 7: True, 8: True, 9: True, 10: True, 11: True, 12: True, 13: True, 14: True, 15: True, 16: True, 17: True, 18: True, 19: True, 20: True, 21: True, 22: True, 23: True, 24: True, 25: False, 26: True, 27: True, 28: True, 29: True, 30: True, 31: True, 32: True, 33: True, 34: True, 35: True, 36: True, 37: True, 38: True, 39: True, 40: True, 41: True, 42: True, 43: True, 44: True}
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Valset pareto front aggregate score: 0.9555555555555556
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Updated valset pareto front programs: {0: {1, 5, 6, 9}, 1: {0, 1, 6, 7, 9, 10}, 2: {10, 6, 7}, 3: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, 4: {6, 7}, 5: {1, 10, 6}, 6: {1, 10, 9}, 7: {0, 1, 2, 4, 5, 6, 7, 9, 10}, 8: {1, 9}, 9: {9, 10}, 10: {1, 6, 8, 9, 10}, 11: {0, 1, 2, 3, 4, 5, 7, 8, 9, 10}, 12: {0, 1, 2, 5, 9, 10}, 13: {8, 1, 2, 7}, 14: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, 15: {2, 6, 7, 8, 9, 10}, 16: {1, 2, 4, 5, 7, 9}, 17: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10}, 18: {3, 5, 6, 7, 10}, 19: {3, 5, 6, 7, 10}, 20: {1, 3, 4, 5, 6, 7, 9}, 21: {1, 3, 4, 5, 6, 7, 8, 9, 10}, 22: {0, 2, 3, 4, 5, 7, 8, 9}, 23: {0, 1, 2, 3, 4, 5, 7, 8, 9, 10}, 24: {0, 1, 2, 3, 9, 10}, 25: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, 26: {2, 3, 5, 6, 7, 9, 10}, 27: {9, 3, 5}, 28: {2, 3, 5, 6, 7, 9, 10}, 29: {2, 3, 5, 7, 9, 10}, 30: {2, 3, 5, 6, 7, 9, 10}, 31: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, 32: {2, 3, 4, 9, 10}, 33: {2, 3, 4, 6, 7, 9, 10}, 34: {2, 3, 4, 5, 7, 9, 10}, 35: {3, 4, 6, 9, 10}, 36: {0, 1, 2, 3, 4, 5, 6, 10}, 37: {0, 4}, 38: {0, 2, 3, 4, 5, 6, 9, 10}, 39: {1, 3, 4, 5, 6, 8, 9, 10}, 40: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, 41: {1, 3, 4, 5, 7, 8, 9, 10}, 42: {8, 2, 3, 4}, 43: {3, 4, 8, 9, 10}, 44: {1, 4, 5, 7, 8, 9, 10}}
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Best valset aggregate score so far: 0.7555555555555555
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Best program as per aggregate score on valset: 9
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Best score on valset: 0.7555555555555555
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Linear pareto front program index: 9
2026/06/06 05:46:05 INFO dspy.teleprompt.gepa.gepa: Iteration 13: New program candidate index: 10
GEPA Optimization:  93%|█████████▎| 519/560 [51:16<04:03,  5.93s/rollouts]

Optimization Complete!

In [36]:
# 1. Redefine the evaluator to guarantee it uses the fresh metric
evaluate_atis = dspy.Evaluate(
    devset=test_examples, 
    metric=my_metric, # Explicitly bind the new metric here
    num_threads=8, 
    display_progress=True, 
    display_table=5, 
    provide_traceback=True
)

# 2. Test your newly optimized model!
# (Assuming you named the output of the GEPA compilation 'optimized_model')
evaluation_score = evaluate_atis(optimized_model)

print(f"Optimized Model Score: {evaluation_score}")

Average Metric: 33.00 / 45 (73.3%): 100%|██████████| 45/45 [03:09<00:00,  4.21s/it]

2026/06/06 05:49:15 INFO dspy.evaluate.evaluate: Average Metric: 33 / 45 (73.3%)

,customer_message,example_answer,intent_labels,reasoning,pred_answer,my_metric
0,find a flight between st. petersburg and charlotte the flight shou...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,The query is asking to find a nonstop flight from St. Petersburg t...,flight+airfare%,✔️ [False]
1,get flights from detroit to toronto,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"The user is requesting a flight query, specifically asking for fli...",flight,✔️ [True]
2,what flights go from phoenix to salt lake city,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"For this query, we can extract that the user wants to know about f...",flight,✔️ [True]
3,list all flights arriving in denver between 8 and 9 pm,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"Based on the customer message ""list all flights arriving in Denver...",airfare+flight_time,✔️ [False]
4,can you find me a flight from salt lake city to new york city next...,flight,flight%flight_time%airfare%aircraft%ground_service%airport%airline...,"The query contains specific time constraints (""next saturday"", ""be...",flight_time,✔️ [False]

Optimized Model Score: EvaluationResult(score=73.33, results=<list of 45 results>)

In [37]:
optimized_model.save("GEPAPrompt.json")

In [ ]:
cot_predictor.parameters()

[Predict(StringSignature(customer_message, intent_labels -> reasoning, answer
     instructions='Classify the customer message into one of the intent labels.\nThe output should be only the predicted class as a single intent label.'
     customer_message = Field(annotation=str required=True json_schema_extra={'desc': 'Customer message during customer service interaction', '__dspy_field_type': 'input', 'IS_TYPE_UNDEFINED': True, 'prefix': 'Customer Message:'})
     intent_labels = Field(annotation=str required=True json_schema_extra={'desc': 'Labels that represent customer intent', '__dspy_field_type': 'input', 'IS_TYPE_UNDEFINED': True, 'prefix': 'Intent Labels:'})
     reasoning = Field(annotation=str required=True json_schema_extra={'desc': '${reasoning}', '__dspy_field_type': 'output', 'prefix': 'Reasoning:'})
     answer = Field(annotation=str required=True json_schema_extra={'desc': "a label best matching customer's intent ", '__dspy_field_type': 'output', 'IS_TYPE_UNDEFINED': True, 'prefix': 'Answer:'})
 ))]

In [ ]:
few_shot_model.demos

In [ ]:
#cot_few_shot_optimized.demos

In [ ]:
#cot_few_shot_rs_optimized.demos

# Remove bootstrapping

In [ ]:
from dspy.evaluate import answer_exact_match as metric
from dspy.teleprompt import BootstrapFewShot

optimizer = BootstrapFewShot(
    metric=metric,
    max_bootstrapped_demos=4, # no need for boostrapped
    max_labeled_demos=40, # increase examples
    max_rounds=20,
)

# documentation is wrong - there is not valset: https://dspy.ai/deep-dive/optimizers/bootstrap-fewshot/
cot_few_shot_to_bootstrap = optimizer.compile(cot_predictor, trainset=train_examples)


evaluate_atis(cot_few_shot_to_bootstrap, metric=metric)
# bootrsapped_demos: generated demos?
# max_labeled_demos: input demos